### ISSUE TITLE
[COR] Plantage à la sauvegarde

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1012]
Url : https://neu.botalista.community/#/corresponding/edit/
Error message : JSON parse error: Cannot deserialize value of type `com.botalista.corresponding.entity.enums.CorrespondingType` from String "garden": value not one of declared Enum instance names: [enum_other, enum_association, enum_private, enum_experimental, enum_commercial, enum_municipality, enum_internal, enum_university, enum_arboretum, enum_seed, enum_garden, enum_expedition]; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.botalista.corresponding.entity.enums.CorrespondingType` from String "garden": value not one of declared Enum instance names: [enum_other, enum_association, enum_private, enum_experimental, enum_commercial, enum_municipality, enum_internal, enum_university, enum_arboretum, enum_seed, enum_garden, enum_expedition]
 at [Source: (PushbackInputStream); line: 1, column: 9] (through reference chain: com.botalista.corresponding.entity.Corresponding["type"])
Username : oppliger

Description : Bonjour,
Cela fait deux fois à deux jours d'intervalle que ça plante lors de la sauvegarde à la création d'un nouveau correspondant.
J'ai rentré les données mercredi en fin de journée, erreur générale.
J'ai repris les mêmes données ce matin, pareil.
Sauvegarde impossible.
SLTS
Laurent

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://neu.botalista.community/api/corresponding/
Request method: POST
Status Code: 405 ()
Data send: 
 {"type":"garden","name":"Grodzisk Podlaski Ogród Ziołowy","code":"GRODZ$","bgciCode":null,"ipen":false,"paying":false,"phone":null,"fax":null,"mail":"edukacja@ziolowyzakatek.pl","web":"https://ziolowyzakatek.pl/Podlaski-Ogrod-Ziolowy,41","correspondingLinks":[],"address":[{"address":null,"additionalAddress":"Koryciny 73b\nPL - 17-315\nGrodzisk"}],"oldID":null,"comment":null,"archive":false}
 Error Type: com.botalista.errors.container.CriticalError
Error message: 
 JSON parse error: Cannot deserialize value of type `com.botalista.corresponding.entity.enums.CorrespondingType` from String "garden": value not one of declared Enum instance names: [enum_other, enum_association, enum_private, enum_experimental, enum_commercial, enum_municipality, enum_internal, enum_university, enum_arboretum, enum_seed, enum_garden, enum_expedition]; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.botalista.corresponding.entity.enums.CorrespondingType` from String "garden": value not one of declared Enum instance names: [enum_other, enum_association, enum_private, enum_experimental, enum_commercial, enum_municipality, enum_internal, enum_university, enum_arboretum, enum_seed, enum_garden, enum_expedition]
 at [Source: (PushbackInputStream); line: 1, column: 9] (through reference chain: com.botalista.corresponding.entity.Corresponding["type"])

**Comment by SiropOps** [comment]
Bonjour Laurent, il semble y avoir un problème sur votre session Botalista. Si vous pouvez utiliser les touches CTL+F5 lorsque vous êtes devant l'écran de Botalista, ça devrait corriger le problème. Merci
