### ISSUE TITLE
[ACQ] BOTA-SA : création de lots (bouton grisé 'Traitement par lot'

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1017]
Url : https://jbp.botalista.community/#/acquisition/list/?q=%25&filters=%7B%22node%22:%7B%22typeEntite%22:%22B%22,%22nodes%22:%5B%7B%22typeEntite%22:%22B%22,%22nodes%22:%5B%7B%22typeEntite%22:%22C%22,%22key%22:%22number%22,%22operator%22:%22startWith%22,%22values%22:%5B%222016%22%5D,%22editing%22:false,%22_flash%22:true%7D%5D,%22logicalOperators%22:%5B%5D%7D,%7B%22typeEntite%22:%22B%22,%22nodes%22:%5B%7B%22typeEntite%22:%22C%22,%22key%22:%22provenanceType%22,%22operator%22:%22equals%22,%22values%22:%5B%22%7B%5C%22version%5C%22:0,%5C%22id%5C%22:0,%5C%22key%5C%22:%5C%22enum_wildcultivated%5C%22,%5C%22value%5C%22:%5C%22label_provenanceType_enum_wildcultivated%5C%22%7D%22%5D,%22editing%22:false,%22_flash%22:true%7D%5D,%22logicalOperators%22:%5B%5D%7D,%7B%22typeEntite%22:%22B%22,%22nodes%22:%5B%7B%22typeEntite%22:%22C%22,%22key%22:%22typeEntite%22,%22operator%22:%22equals%22,%22values%22:%5B%22%7B%5C%22version%5C%22:0,%5C%22id%5C%22:0,%5C%22key%5C%22:%5C%22G%5C%22,%5C%22value%5C%22:%5C%22label_typeEntite_G%5C%22%7D%22%5D,%22editing%22:false,%22_flash%22:true%7D%5D,%22logicalOperators%22:%5B%5D%7D%5D,%22logicalOperators%22:%5B%22and%22,%22and%22%5D%7D,%22editing%22:false,%22saved%22:false,%22name%22:%22%22%7D
Username : paris

Description : Bonjour Cyril, 
Le bouton 'Traitement par lot' est grisé pour les SA de 2016 sauvage (cultivé) et sauvage. Cependant, j'ai pu traiter tous les SA Jardin (soit 133). Je te fournirai les captures correspondantes. 
Bien à toi 
Vincent Lipa

**Comment by Paris75012** [comment]
![Traitement par lot_Type_Sauvage_Cultivé_SA_2016](https://user-images.githubusercontent.com/74540524/160134011-4dedd002-1678-4883-bea1-f5fc2cbfc6a1.png)
![Traitement par lot_Type_Sauvage_SA_2016](https://user-images.githubusercontent.com/74540524/160134016-3b4a92ef-2d38-46d2-a107-5299c374d645.png)
![Traitement par lot_Type_Sauvage_SA_2016](https://user-images.githubusercontent.com/74540524/160134023-26cf281e-a11b-40fd-a6f6-06c74633ee73.png)
![Traitement par lot_Type_Sauvage_Cultivé_SA_2016](https://user-images.githubusercontent.com/74540524/160134026-677dd7b2-a57c-44db-92c4-80493dc8db81.png)

**Comment by SiropOps** [comment]
Bonjour Vincent, il manque effectivement un label, mais on peut envoyer que maximum de 250 résultat de la recherche, je rajoute.
++
