### ISSUE TITLE
[CULT] bug auto-filtre dans mise en collection

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1029]
Url : https://ncy.botalista.community/#/cultivated/view/156698
Username : berthold

Description : Salut Cyril,
Quelque chose qui n'était pas las il y a quelques jours:
Quand crée une nouvelle multi et je fais mise en collection le champ "Emplacement" à déjà un filtre pré-désigné dessus sur le Chitelet. Normalement il ne doit pas avoir de "préfiltre" dessus - tu connais l'origine de cette nouveauté?
Bon weekend,
Carl

**Comment by SiropOps** [comment]
Il faut changer, dans Secteur actif et passer en Tous les secteurs pour désectiver ce filtre.

++
