### ISSUE TITLE
[NOM] Blocage au milieu d'une nomenclature

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1041]
Url : https://g.botalista.community/#/nomenclature/edit/45080
Username : lehmann

Description : Jamais vu cet écran avant et déjà deux fois aujourd'hui.

Comprends pas. Bug ? Erreur de ma part ?

Impossible d'aller plus loin. Message : Voulez-vous tout de même sauvegarder ?"
Droit(s) nécessaire(s)

Catalogue EN ROUGE
Cat. Jardin EN VERT
Conservation EN VERT
Entretien général et dendrologie EN VERT

Cette action aura un effet sur les taxons suivants :

1. Syringa josikaea J. Jacq. Droits nécessaire Cat. Jardin - Conservation

Cette action aura un effet sur les taxons suivants :

19800327/Syringa josikea J. Jacq. f. Droits nécessaires Entretien Général et Dendrologie.

**Comment by SiropOps** [comment]
Rien d'inédit, le système vérifie les droits et en modifiant ce nom, tu vas modifier des acquisitions de l'ancien secteur Catalgue auquel tu n'as pas les droits
