### ISSUE TITLE
[NOM] Absence de Droits nécessaires

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1043]
Url : https://g.botalista.community/#/nomenclature/view/404312?tab=2
Username : lehmann

Description : Je veux rentrer cette synonymie pour coller à WFO qui est notre référence.
Impossible de sauvegarder.
Il semble que je n'ai pas les droits sur "Catalogue".
Quoi faire ?
Est-ce que cette limitation est une nouveauté ? Je suis coincée pour la seconde fois en très peu de temps alors que cela ne m'arrivait jamais auparavant ? Hasard ?

Est-ce qu'il y a moyen de joindre des captures d'écran pour illustrer mieux le problème lors d'envois de tickets ?

Merci d'avance.
al

**Comment by RPalese** [comment]
Hello Alexanne,
Il te suffit de glisser l'image là où tu écris.
J'attends donc la capture d'écran ;-)
