### ISSUE TITLE
[ACQ] BOTA-SC : Lien hypertexte du parent défaillant

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1049]
Url : https://jbp.botalista.community/#/acquisition/view/52723
Username : paris

Description : Bonjour les DEV de BOTALISTA,

Le lien hypertexte du parent 20196218C0 est défaillant. Il n'aboutit pas au Parent recherché (ici 20196218C0).

Cordialement 

Vincent Lipa

**Comment by Paris75012** [comment]
![Screenshot_2022-05-12 Botalista Acquisitions Consultation 52723](https://user-images.githubusercontent.com/74540524/168076311-0b4acb85-c536-4a7f-a9c2-5b2e4c527f85.png)
![Screenshot_2022-05-12 Botalista Acquisitions Consultation 52723_](https://user-images.githubusercontent.com/74540524/168076355-23bbbce5-fdcd-43fd-9248-e66076e73154.png)

**Comment by Paris75012** [comment]
![Screenshot_2022-05-12 Botalista Acquisitions Consultation 52723_3](https://user-images.githubusercontent.com/74540524/168077131-516b95c8-74b3-4f73-9bb6-eec8bbdee458.png)
