### ISSUE TITLE
[ACQ] Récolte impossible !!!!

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1057]
Url : https://g.botalista.community/#/acquisition/edit/66316
Username : lehmann

Description : Impossible de faire une récolte dans la province de Quebec !
Le système me propose pourtant "Quebec, état". Mais ensuite, ça mouline sans fin.
J'ai essayé de rentrer par "Canada" puis de préciser à la souris. Même topo ! J'ai tenté le coup au moins 10 fois. Je suis sortie du programme et j'ai recommencé. Aucun résultat.

Merci d'avance.
al

**Comment by SiropOps** [comment]
Le polygone du Québec est assez gros, il faut être patient ;-) 

++

Cyril
