### ISSUE TITLE
[lot] BOTA-IS : Comment retirer des lots de l'Index seminum ?

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1074]
Url : https://jbp.botalista.community/v2/fr/lot/list
Username : paris

Description : Bonjour les DEV de Botalista, 
Le lot 20178804G0 est affiché dans l'Index seminum. Comment le retirer de la liste de l'Index seminum ?
Cordialement 
VIncent Lipa

**Comment by Paris75012** [comment]
Bonjour les DEV de Botalista, 
J'ai coché puis décoché la case 'Présence dans l'IS'. Ce lot est  toujours présent dans l'Index seminum

Cordialement 
VIncent Lipa

**Comment by RPalese** [comment]
Hello Vincent,
Je ne vois pas le lot 20178804G dans ton IS et il est bien désélectionné. Donc pas de problème de mon côté.
Raoul

**Comment by Paris75012** [comment]
Bonjour Raoul, 
ce lot est toujours présent dans mon IS référencé sous l'IPEN CH0G-20150943. Par contre, il est bien désélectionné.

**Comment by Paris75012** [comment]
[indexSeminumJBPDocxReport.docx](https://github.com/Computaceae-IT/cit-ticketing/files/9394022/indexSeminumJBPDocxReport.docx)

**Comment by Paris75012** [comment]
Caryophyllaceae | 1111 | Dianthus sylvestris Wulfen | CH0G-20150943 | Suisse | Valais |  
SA N° : 20178804G

**Comment by Paris75012** [comment]
Bonjour Les DEV de BOTALISTA, 
Je n'arrive toujours pas à supprimer ce lot. Il est décoché dans l'édition du lot de graines. Mais celui-ci est toujours présent dans l'IS

**Comment by Paris75012** [comment]
Rebonjour les DEV, 
j'ai pu supprimer ce lot de l'IS en supprimant le lot de semences. Cependant, tous les Dianthus sylvestris (des autres années) pnt disparu de l'IS !!  
Cordialement 
Vincent Lipa
