### ISSUE TITLE
[LOC] édition des polygones des emplacements

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1084]
Url : https://neu.botalista.community/#/location/view/3?tab=2
Username : maire

Description : Bonjour,

Pour créer les polygones des emplacements, je peux vous transmettre un fichier shapefile ou autre format ? J'en fais un par groupe ? un par sous groupe ? J'ai testé l'édition dans botalista et je trouve qu'on ne peut pas faire des lignes très précises (prend du temps).
Merci pour votre réponse !

Merci

**Comment by RPalese** [comment]
Hello Anne-Laure,
Des fichiers shapefile c'est parfait!
Par groupe ou par sous-groupe cela dépend uniquement de toi et de la résolution que tu souhaites avoir visuellement.
A très bientôt
Raoul
