### ISSUE TITLE
[NOM] Impossible de sauvegarder - la base réclame les droits de l'Herbier alors que je rentre une plante pour le JARDIN

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1096]
Url : https://g.botalista.community/#/nomenclature/edit/448422
Username : lehmann

Description : La base bloque la sauvegarde en réclamant les droits de l'Herbier.
Je suis certaine de ma saisie. Je devrais pouvoir rentrer cette plante pour le Jardin.

**Comment by SiropOps** [comment]
Il faut juste se déconnecter / reconnecter ;-)
