### ISSUE TITLE
[REC] Ajout d'un TRADE INDEX

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1098]
Url : https://ncy.botalista.community/#/harvest/list/
Username : beghoura

Description : Il serait intéressant d'avoir un TRADE INDEX qui reprendrait les mêmes fonctionnalités que pour les autres secteurs

**Comment by SiropOps** [comment]
Cest fait "TRADE_ACQ_Index seminum" Je te laisse l'affecter aux utilisatuers suivant la marche à suivre https://wiki.botalista.community/bin/view/Computaceae-IT/Botalista/Documentation/BOTA-USR/
