### ISSUE TITLE
[EXP] Modif du modèle d'export

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1104]
Url : https://ncy.botalista.community/v2/fr/exportation/template/edit/id/6135e8a94606f500015cf0f6
Username : beghoura

Description : null

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://ncy.botalista.community/api/exportation/template/
Request method: POST
Status Code: 405 (Http failure response for https://ncy.botalista.community/api/exportation/template/: 405 OK)
Data send: 
 {"id":"6135e8a94606f500015cf0f6","uid":"f19e195c-a389-4019-8dcf-57f4bd8e8295","version":0,"name":"Base","createAt":"2021-09-06T10:08:41.232+00:00","createBy":"sibadmin","updateAt":"2021-09-13T14:26:26.320+00:00","columns":[{"key":"number","order":30,"length":0,"scale":0,"precision":0,"requiered":false,"translates":{"de":"Nummer des kultivierten Exemplars","en":"Cultivated specimen number","fr":"Numéro de spécimen cultivé"},"translatedValue":"Numéro de spécimen cultivé"},{"key":"family","order":60,"length":0,"scale":0,"precision":0,"requiered":false,"translates":{"de":"Familie","en":"Family","fr":"Famille"},"translatedValue":"Famille"},{"key":"genus","order":70,"length":0,"scale":0,"precision":0,"requiered":false,"translates":{"de":"Gattung","en":"Genus","fr":"Genre"},"translatedValue":"Genre"},{"key":"species","order":80,"length":0,"scale":0,"precision":0,"requiered":false,"translates":{"de":"Art","en":"Species","fr":"Espèce"},"translatedValue":"Espèce"},{"key":"infraSpecies","order":90,"length":0,"scale":0,"precision":0,"requiered":false,"translates":{"de":"Unterart","en":"Infra Species","fr":"Sous-espèce"},"translatedValue":"Sous-espèce"},{"key":"cultivar","order":100,"length":0,"scale":0,"precision":0,"requiered":false,"translates":{"de":"Kultivar","en":"Cultivar","fr":"Cultivar"},"translatedValue":"Cultivar"},{"key":"area","order":140,"length":0,"scale":0,"precision":0,"requiered":false,"translates":{"de":"Bereich","en":"Area","fr":"Aire"},"translatedValue":"Aire"},{"key":"place","order":150,"length":0,"scale":0,"precision":0,"requiered":false,"translates":{"de":"Gruppe","en":"Group","fr":"Groupe"},"translatedValue":"Groupe"},{"key":"groupe","order":160,"length":0,"scale":0,"precision":0,"requiered":false,"translates":{"de":"Untergruppe","en":"Sub-group","fr":"Sous-groupe"},"translatedValue":"Sous-groupe"},{"key":"correspondingName","order":301,"length":0,"scale":0,"precision":0,"requiered":false,"translates":{"de":"Korrespondent","en":"Correspondent","fr":"Correspondant"},"translatedValue":"Correspondant"},{"key":"provenanceType","order":250,"length":0,"scale":0,"precision":0,"requiered":false,"translates":{"de":"Herkunftstyp","en":"Provenance type","fr":"Type de provenance"},"translatedValue":"Type de provenance"},{"key":"areaRepartition","order":290,"length":0,"scale":0,"precision":0,"requiered":false,"translates":{"de":"Verbreitungsgebiet","en":"Distribution area","fr":"Aire de distribution"},"translatedValue":"Aire de distribution"}],"createAtToString":"06-09-2021 12:08:41","updateAtToString":"13-09-2021 16:26:26"}
 Error Type: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":405,"statusText":"OK","url":"https://ncy.botalista.community/api/exportation/template/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://ncy.botalista.community/api/exportation/template/: 405 OK","error":{"error":{"entityType":"CRITICAL_ERROR","msg":"org.springframework.dao.DuplicateKeyException: E11000 duplicate key error collection: ncy_bota_exp_prd.template index: _id_ dup key: { _id: ObjectId('6135e8a94606f500015cf0f6') }; nested exception is com.mongodb.MongoWriteException: E11000 duplicate key error collection: ncy_bota_exp_prd.template index: _id_ dup key: { _id: ObjectId('6135e8a94606f500015cf0f6') }","date":"2022-08-25T13:08:04.945+00:00"}}}
Error message: 
 {"entityType":"CriticalError","key":"","value":"","msg":"org.springframework.dao.DuplicateKeyException: E11000 duplicate key error collection: ncy_bota_exp_prd.template index: _id_ dup key: { _id: ObjectId('6135e8a94606f500015cf0f6') }; nested exception is com.mongodb.MongoWriteException: E11000 duplicate key error collection: ncy_bota_exp_prd.template index: _id_ dup key: { _id: ObjectId('6135e8a94606f500015cf0f6') }","values":[],"date":"2022-08-25T13:08:04.945+00:00"}

**Comment by SiropOps** [comment]
Problème en base de données
