### ISSUE TITLE
[LOC] impossible de rechercher un emplacement par secteur

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1111]
Url : https://ncy.botalista.community/#/location/list/?filters=%7B%22type%22:%22custom%22,%22key%22:%22sector%22%7D
Username : philippe chauvet

Description : Hello Cyril,
Je suis au Chitelet avec Philippe et nous venons de nous rendre compte qu'il ne lui ait pas possible de rechercher un emplacement par secteur alors qu'il a les autorisations.
Même problème qu'énoncé hier, le champ est grisé, peut être dû au conflit lecture / écriture.

Tout de bon

**Comment by SiropOps** [comment]
C'est normal, cet écran sert à afficher tous les emplacement par secteur. Si on veux une recherche par secteur, il faut se servir des filtres.

++
