### ISSUE TITLE
[LOC] bug emplacement

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1114]
Url : https://ncy.botalista.community/#/location/view/105?tab=3
Username : beghoura

Description : Je viens de changer le nom d'une Aire de C.  Asie vers Asie centrale.
Aucuns soucis pour la modification de l'emplacement mais la colonne aire des spécimens cultivés liés ne se met pas à jour.

**Comment by SiropOps** [comment]
ça marche, la propagation des changement peut prendre quelques minutes suivant la charge sur les serveurs
