### ISSUE TITLE
[NOM] Hybrids and taxonomic rank

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1120]
Url : https://briss.botalista.community/#/nomenclature/edit/
Username : maccagni

Description : Hi Cyril, I was trying to enter the hybrid as you told me from Taxon, but it seems that it can only go up to familia rank (no longer below), is this normal?

Thanks and regards, Ale

**Comment by SiropOps** [comment]
https://user-images.githubusercontent.com/35902374/191285900-5d89f538-ab5f-4292-af2d-9dd2c1f2f1f8.mp4
