### ISSUE TITLE
[NOM] impossibilité de mettre ce nom comme accepté courant

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1122]
Url : https://g.botalista.community/#/nomenclature/view/112409?tab=2
Error message : could not execute statement; SQL [n/a]; constraint [ind_names_taxon_unique]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Username : buchschacher

Description : que l'on passe par Ptilotrichum spinosum ou par Alyssum spinosum impossible de définir Ptilotrichum spinosum comme nom accepté courant

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://g.botalista.community/api/nomenclature/synonym/process/force/
Request method: POST
Status Code: 405 (Method Not Allowed)
Data send: 
 {"idNodeParent":112409,"pov":2,"mode":"switch"}
 Error Type: com.botalista.lib.core.errors.container.CriticalError
Error message: 
 could not execute statement; SQL [n/a]; constraint [ind_names_taxon_unique]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by SiropOps** [comment]
Pareil, corrigé ;-)
