### ISSUE TITLE
[LOC] probleme emplacement

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1126]
Url : https://neu.botalista.community/#/location/view/88?tab=3
Username : maire

Description : Salut,
C'est la deuxième fois que j0ai ce problème avec un emplacement, je mets mes spécimens cultivés dans l'emplacement, quand je les consultes, ils sont bien lié à cet emplacement, mais quand je vais sous l'emplacement, j'ai 0 spécimen cultivés liés.
Il s'agit de : groupe : Jardin expérimental sous-groupe : Absinthe
Merci d'avance !

**Comment by SiropOps** [comment]
Coucou, j'ai pas réussi à trouver des SC dans ce sous-groupe. Pourrais-tu me donner des numéros de SC stp ? Merci d'avnace.

++

**Comment by al-maire** [comment]
non en effet, il n'y en a aucun dans le sous-groupe, c'est le problème.
Mais si je consulte les SC, j'ai dans l'affichage qu'ile st dans le sous-groupe, pex pour le Sc suivant et la capture d'écran ci-joint.
https://neu.botalista.community/#/cultivated/view/55435
![empla_SC](https://user-images.githubusercontent.com/74531240/191230552-2c736be6-7ca0-419a-ad2c-d13f604080a7.PNG)

pareil pour cwe SC aussi 👍 https://neu.botalista.community/#/cultivated/view/55439
20210477N0

ou celui là:
20210476J0 

Merci,
