### ISSUE TITLE
[NOM] Impossiblilité de changer un nom accepté courant

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1127]
Url : https://g.botalista.community/#/nomenclature/view/22681?tab=2
Error message : could not execute statement; SQL [n/a]; constraint [ind_names_taxon_unique]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Username : buchschacher

Description : Même bog que le dernier, impossible de définir un nom comme nom accepté courant ! J'aimerai Stachys officinalis comme nom principal.

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://g.botalista.community/api/nomenclature/synonym/process/force/
Request method: POST
Status Code: 405 (Method Not Allowed)
Data send: 
 {"idNodeParent":22681,"pov":2,"mode":"switch"}
 Error Type: com.botalista.lib.core.errors.container.CriticalError
Error message: 
 could not execute statement; SQL [n/a]; constraint [ind_names_taxon_unique]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by SiropOps** [comment]
C'est tout bon, c'était un peu le bordel dans la base; j'ai tout nettoyé.

++
