### ISSUE TITLE
[NOM] Bug à l'import?

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1137]
Url : https://ncy.botalista.community/#/nomenclature/view/154210?tab=1
Username : beghoura

Description : Cyril, je viens de me rendre compte que des espaces se sont glissés après les points. 
Est-ce un bug?

**Comment by SiropOps** [comment]
Non, c'est un relica des données de Genève, j'ai corrrigé cela lors dans la migration des noms de la WFO. Je laisse cette nouvelle version la semaine prochaine ;-)
