### ISSUE TITLE
[ACQ] suppression acquisition

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1142]
Url : https://g.botalista.community/#/acquisition/edit/67277
Username : buchschacher

Description : J'aimerai supprimer cette acquisition en G, dupliccata de l'acquisition de base en J (a garder), impossible de le faire = lien avec lot de semences que l'on arrive pas à supprimer.

**Comment by SiropOps** [comment]
https://user-images.githubusercontent.com/35902374/204770200-8e09e3ab-a5bb-415f-89a2-df84137f4783.mp4
