### ISSUE TITLE
[IND] BOTA-IS : Comment puis-je supprimer un numéro d'IS depuis l'Index Seminum

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1148]
Url : https://jbp.botalista.community/v2/fr/indexseminum/list
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Cette nouvelle 'commande' (Supprimer tous les numéros d'IS)  permet de supprimer tous les numéros d’IS. Comment puis-je supprimer seulement  un lot de semences  dans l’IS de BOTALISTA ?

Cordialement 
Vincent Lipa

**Comment by SiropOps** [comment]
Regardez https://github.com/Computaceae-IT/cit-ticketing/issues/1142
