### ISSUE TITLE
[S.L] BOTA-ACQ : ouverture de la vue 'Edition d'une récolte' provoque le plantage de l'application

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1152]
Url : https://jbp.botalista.community/#/
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

L'ouverture de la vue 'Edition d'une récolte' depuis BOTA-ACQ aboutit au plantage de l'application. Il est impossible de fermer l'application.

Cordialement 
Vincent Lipa

**Comment by Paris75012** [comment]
[TICKET_1152_Plantage Application.docx](https://github.com/Computaceae-IT/cit-ticketing/files/10133024/TICKET_1152_Plantage.Application.docx)
