### ISSUE TITLE
[NOM] Rang taxonomique inférieur famille

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1166]
Url : https://briss.botalista.community/#/nomenclature/edit/
Username : maccagni

Description : Salut Cyril, j'espère que tout va bien. 
J'essayais de créer des cultivars et des hybrides, mais je vois que je n'ai pas la possibilité d'accéder à un rang taxonomique inférieur à la famille. Quelle est la procédure à suivre ?

Cordialement, Ale

**Comment by SiropOps** [comment]
https://user-images.githubusercontent.com/35902374/207540664-49e10770-62e0-4367-9d6d-47cd677139b8.mp4
