### ISSUE TITLE
[CULT] plantage lors de la recherche du nom d'acquisition

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1171]
Url : https://jbp.botalista.community/#/cultivated/edit/
Username : demesse

Description : impossible de trouver le nom d'acquisition. recherche sans fin lors de l'entrée des premières lettres du nom d'acquisition puis bug

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://jbp.botalista.community/api/nomenclature/taxon/autocomplete/Taxodium%20di/pov/2
Request method: GET
Status Code: -1 ()
Data send: 
 undefined
 Error Type: 
Error message:

**Comment by SiropOps** [comment]
Impossible a reproduire
