### ISSUE TITLE
[S.L] BOTA-ADMIN : nouveaux utilisateurs non reconnus

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1173]
Url : https://jbp.botalista.community/#/
Username : paris

Description : Bonjour les DEV de BOTALISTA,
 
Je viens de reconstruire deux comptes utilisateurs désignés ci-contre : gensous et plumet_colomb. Le mot de passe temporaire attribué est « Paris ». Or le système ne connait pas ces deux nouveaux utilisateurs à partir de leurs courriels ou noms d’utilisateurs.

Cordialement 
Vincent Lipa

**Comment by SiropOps** [comment]
![image](https://user-images.githubusercontent.com/35902374/209688617-89f7f18e-dc46-402c-a85c-301d6348273b.png)

**Comment by SiropOps** [comment]
Pas de problèmes constacté. Attention à la case
