### ISSUE TITLE
[CULT] Actualisation des emplacements dans "mise en collection" ne se fait pas

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1186]
Url : https://ncy.botalista.community/#/cultivated/view/144783
Username : beghoura

Description : Hey,

Tout est dans le titre ;)

**Comment by SiropOps** [comment]
C'est n'est pas un bug. Si tu mets en collection dans un emplacement, puis tu le changes de localisation, il conserve sa mise en collection initiale, comme historique.
