### ISSUE TITLE
[ACQ] Impossible de lier un nom

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1195]
Url : https://g.botalista.community/#/acquisition/edit/
Username : mentha

Description : Aussi sur Sandbox

**Comment by SiropOps** [comment]
Hello,
Sur la sandbox, je vois pas le problème. Par contre, sur l'instance de G, c'est normal, tu n'as aucun droit sur les secteurs; donc impossible de créer des acquisitions sans avoir au moins un secteur actif. Je te laisse aller voir vers la personne qui t'a créé ton profil pour savoir sur quels secteurs tu as des droits.

Tout de bon
