### ISSUE TITLE
[ORD] Lorsque l'on édite le désidérata de commande de graine, le mail ne fonctionne pas

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1202]
Url : https://bord.botalista.community/#/order/catalog/view/88
Username : kassen

Description : lorsque le désiderata s'édite, le mail ne s'ouvre pas automatiquement,

merci

**Comment by SiropOps** [comment]
Il suffit de cliquer sur l'enveloppe pour ouvrir le mail

![image](https://user-images.githubusercontent.com/35902374/213401832-ab4f2531-6eee-4ffa-9784-a39e70e68e9e.png)
