### ISSUE TITLE
[ACQ] Erreur de pays

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1210]
Url : https://briss.botalista.community/#/acquisition/edit/
Username : maccagni

Description : Setting IPEN with 'NZ' does not find New Zealand in the country list (and even scrolling with 'N' does not find this country). 
I have also noticed that errors often occur where Sri-Lanka is assigned (e.g., with collections in Tenerife instead of Spain; or Syria instead of Switzerland) despite being the wrong nation.

**Comment by SiropOps** [comment]
I just want to ckeck data this week, but the bug is fixed
