### ISSUE TITLE
[NOM] BOTA-NOM : suppression du nom Kniphofia uvaria (L .) Oken ‘Royal Castle’

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1213]
Url : https://jbp.botalista.community/#/nomenclature/edit/446523
Username : paris

Description : Bonjour Les DEV de Botalista, 

Je souhaiterai supprimer ce nom (Kniphofia uvaria (L .) Oken ‘Royal Castle’ de BOTA-NOM. Mais le système m’indique que l’opération est impossible.

Pourrais-tu me le supprimer de BOTA-NOM ? 

Il manque un bouton de suppression dans le formulaire lié à BOTA-TAX.

Cordialement 

Vincent Lipa

**Comment by SiropOps** [comment]
https://user-images.githubusercontent.com/35902374/220378121-7cc9eb7e-1a6f-4118-ae5b-5ab38d234355.mp4
