### ISSUE TITLE
[EXP] BOTA-SC : signification du champ 'Familie Hybride' dans l'export Excel

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1218]
Url : https://jbp.botalista.community/v2/fr/exportation/template/edit
Username : paris

Description : Bonjour les DEV de BOTALISTA, 
Que signifie ce champ ? 
Cordialement, 
Vincent Lipa

**Comment by SiropOps** [comment]
Il y a pas d’hybridation dans les famille ?! ;-)

C'est effectivement une erreur, je le supprime.

Bien à toi, Cyril
