### ISSUE TITLE
[CULT] BOTA-ADMIN : Modèle d'export

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1219]
Url : https://jbp.botalista.community/#/cultivated/view/8320
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Suite à une demande d'une utilisatrice de Botalista, j'ai activé le module BU_Admin dans les rôles de l'utilisatrice de Nathalie Faire.Le modèle d'export apparait dans le menu BOTA-ADMIN de l'utilisatrice. Cependant, d'autres menus (Import CSV, Configuration et Configuration des variables)  sont affichés. Ces menus sont identiques à celui du menu BOTA-ADMIN de l'administrateur).

Comment masquer ces 3 menus ?

Cordialement, 
Vincent Lipa

**Comment by Paris75012** [comment]
![Screenshot 2023-02-23 at 14-55-08 Botalista_Spécimens cultivés_Consultation_8320](https://user-images.githubusercontent.com/74540524/220927989-16a92486-1bb0-46ef-85d5-67c48952d93f.png)

**Comment by Paris75012** [comment]
![BOTA_ADMIN_NATHALIE_FAIVRE](https://user-images.githubusercontent.com/74540524/220928251-4bdc5fdb-3f5a-46fc-bae2-2a95699f2853.png)

**Comment by SiropOps** [comment]
Bonjour Vincent, pour l'instant il n'est pas possible de masquer ces 3 menus. Lorsqu'on donne les droit admin, tous les modules d'administration apparaissent. Si tu le souhaite, Je te propose de faire ticket d'évolution en spécifiant combien de profil il te faut et ce qui doit apparaitre. par exemple 
ADMIN_1 -> Modèle d'export
ADMIN_2 -> Modèle d'export, Import CSV
ADMIN_3 -> ... etc.

Merci, et bien à toi

**Comment by Paris75012** [comment]
Cyril,

2 profils :

ADMIN_1 -> Modèle d'export
ADMIN_2 -> Modèle d'export, Import CSV

Merci beaucoup,

Bien à toi,

Vincent Lipa
Responsable de la graineterie du JBP

***@***.***

Jardin botanique de Paris – Paris.fr<https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiYgMnC0qXaAhXIkywKHcbyAL4QFgguMAA&url=https%3A%2F%2Fwww.paris.fr%2Fjardinbotaniquedeparis&usg=AOvVaw108ymee_CTrfV65b7K05nw>

Bureau :
Ville de Paris
Direction des Espaces Verts et de l'Environnement
Services des Techniques du Végétal et de l’Agriculture
Jardin Botanique
103 avenue de  France
75639 PARIS Cedex 13
Fax : + 33 (0)1 71 28 57 41

Graineterie du Jardin botanique de Paris :
Pavillon 5 - Parc Floral  75012 Paris
Tél. : + 33 (0)1 49 57 94 47

De : Cyril Boillat ***@***.***
Envoyé : mardi 7 mars 2023 10:26
À : Computaceae-IT/cit-ticketing ***@***.***>
Cc : Lipa, Vincent ***@***.***>; Comment ***@***.***>
Objet : Re: [Computaceae-IT/cit-ticketing] [CULT] BOTA-ADMIN : Modèle d'export (Issue #1219)

* Ce message a ete emis par un expediteur externe *
Prenez garde aux liens et aux pieces jointes. Ne fournissez jamais votre mot de passe de connexion Ville de Paris.

________________________________

Bonjour Vincent, pour l'instant il n'est pas possible de masquer ces 3 menus. Lorsqu'on donne les droit admin, tous les modules d'administration apparaissent. Si tu le souhaite, Je te propose de faire ticket d'évolution en spécifiant combien de profil il te faut et ce qui doit apparaitre. par exemple
ADMIN_1 -> Modèle d'export
ADMIN_2 -> Modèle d'export, Import CSV
ADMIN_3 -> ... etc.

Merci, et bien à toi
