### ISSUE TITLE
[CULT] Explication Mise en collection

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1221]
Url : https://ncy.botalista.community/#/cultivated/view/146104
Username : berthold

Description : Salut Cyril
Je suis en train de bouger toute un collection d'un groupe "Pélargoniums" dans le groupe "Gradins Pélargos Est (Vivaces)". J'ai aussi mis à jour le nombre de plantes dans "Mise en collection" mais l'emplacement ici dis toujours Pélargoniums lorsque que l'emplacement dit Gradins Pélargos Est (Vivaces)....
J'ai mal compris l'usage de ce champ?
Merci d'avance

**Comment by SiropOps** [comment]
Hello Carl,
"oui" ;-) l'emplacement dans Mise en collection est le premier emplacement que la plante à porté. L'idée était, en un regard, de pouvoir voir l'emplacement initial des spécimens. 

L'emplacement courrant tu le retrouve toujours en haut. Voir capture d'écran ci dessous.

Bien à toi, Cyril

**Comment by SiropOps** [comment]
![image](https://user-images.githubusercontent.com/35902374/223374728-93c5ab75-2464-4064-807e-42507c5b536f.png)
