### ISSUE TITLE
[FUN] BOTA-ADMIN : Keycloak

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1230]
Url : https://jbp.botalista.community/#/functionalunit/edit/27
Username : paris

Description : Bonjour les DEV de BOTALISTA,

Je vous remercie de bien vouloir supprimer dans 'Available Roles' les TRADES ci-dessous : 

"TRADE ACQ_serre plateau" 

"TRADE ACQ  Serre Plateau"

le bon TRADE ACQ est "Serre Plateau"

Cordialement 

Vincent Lipa

**Comment by Paris75012** [comment]
le bon TRADE ACQ est "Serre plateau" !!!
