### ISSUE TITLE
[ACQ] BOTA-ACQ : Edition impossible du SA  20211371G

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1240]
Url : https://jbp.botalista.community/#/acquisition/view/52499
Username : paris

Description : Bonjour les Dev de Botalista, 

Je n'arrive pas à éditer le SA 20211371G. La "roue" du système de BOTALISTA tourne en permanence.

Cordialement 

VIncent Lipa

**Comment by Paris75012** [comment]
![image](https://user-images.githubusercontent.com/74540524/233965048-50906162-0bbb-4b9a-a77f-e30533b74fc1.png)
