### ISSUE TITLE
[ACQ] BOTA-SC : anomalie  cultivated_viewForModale_title

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1243]
Url : https://jbp.botalista.community/#/acquisition/view/54785
Username : paris

Description : Bonjour les DEV de Botalista, 

Je rencontre ce bug gênant lorsque je clique sur le lien hypertexte du parent (ex : 2018201N0) du Pelargonium capitatum 20220626G. Il apparait 2 vues successives 'cultivated_viewForModale_title et Champ de recherche du SC parent.  

Cordialement, 
Vincent Lipa

**Comment by Paris75012** [comment]
![image](https://user-images.githubusercontent.com/74540524/236398385-faf93130-a919-4138-8649-135b1eae823a.png)

**Comment by Paris75012** [comment]
![image](https://user-images.githubusercontent.com/74540524/236398428-e5824e6f-b73a-49b9-91e9-b905e84c8dbf.png)
