### ISSUE TITLE
[NOM] Impossible de modifier les rôle d'un utilisateur

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1250]
Url : https://ncy.botalista.community/#/nomenclature/view/1518206?tab=1
Username : beghoura

Description : Sur Sib_admin, je ne peux pas modifier le rôle des administrateurs.

**Comment by SiropOps** [comment]
Normal, cette utilisateur est l'utilisateur Root et ne peut pas pas être modifier ;-)
