### ISSUE TITLE
[NOM] Impossible d'ajouter une citation d'auteur

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1251]
Url : https://ncy.botalista.community/#/nomenclature/view/1518206?tab=1
Username : beghoura

Description : Impossible d'ajouter un auteur à un nom (le champ est vide)

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/09d9692d-f9e8-4a73-82c3-f9774b7e880c
