### ISSUE TITLE
[CULT] Impression étiquette code QR illisible

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1259]
Url : https://g.botalista.community/#/cultivated/view/61710
Username : buchschacher

Description : Le code QR de ce spécimen n'est pas lisible avec la douchette, sort très différent des codes QR habituels.

**Comment by RPalese** [comment]
Mail de Céline le 27.06.2023:
Vincent  G. m'a fait remarquer sur l'une des acquisition faite ce matin la chose suivante (qui en fait est le cas pour toutes les acquisitions dans Botalista !)

Les QR codes des étiquettes de propagation ne sortent plus pareil et sont illisibles par les collègues qui les utilisent sur les étiquettes de culture.

Cela depuis aujourd'hui et pour toute nouvelle impression / exportation de l'étiquette de propagation.

J'ai fait un ticket pour l'une des étiquettes qui posait problème mais pas pour Botalista en général.

**Comment by SiropOps** [comment]
Merci de re-créer les étiquettes produites depuis la version 5.0.3 (25.06.2023 à 20h)
