### ISSUE TITLE
[PER] Nom supplémentaire avec nom = 'NA PAS SUPPRIMER'

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1278]
Url : https://g.botalista.community/v2/fr/person/edit/uid/6b88a59c-074c-44a1-ac85-1b0db90a0e9f
Username : sibadmin

Description : Pourquoi certaines personnes ont un nom supplémentaire avec nom de famille = 'NA PAS SUPPRIMER'?
Effet collatéral: on ne peut pas modifier ces personnes puisque le prénom est vide.

**Comment by RPalese** [comment]
![NAPASSUPPRIMER](https://github.com/Computaceae-IT/cit-ticketing/assets/37696294/04195ce3-33fe-4fe5-b037-1731b33efe85)

**Comment by stevenliatti** [comment]
Problème résolu, le nom alternatif "NA PAS SUPPRIMER" a été supprimé des personnes concernées :+1:
