### ISSUE TITLE
[REC] Informations non migrées

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1282]
Url : https://g.botalista.community/#/harvest/view/8149
Username : palese

Description : Pour cette récolte dans la "Bleue" on a l'information dans le champ "Localité selon étiquette": Satigny S 13. Pourquoi on ne retrouve pas cette information dans le BLS?

**Comment by SiropOps** [comment]
Le champ ETIQUETTE_ORIG qui, je suppose, contient la "localité selon étiquette" n'a pas fait l’objet d'une migration. Si des informations supplémentaires devrait être ajoutées à la migration, il faut augmenter et remplir le Template existant sur les récoltes. Il pourrait aussi être utile à la migration des récolter HER.
