### ISSUE TITLE
[LOC] BOTA-SC : cartographie - vue de l'emplacement après l'enregistrement du groupe

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1283]
Url : https://jbp.botalista.community/#/location/view/6234?tab=2
Username : paris

Description : Bonjour les DEV,
 
Après l'enregistrement du polygone du groupe "Plante bande collection historiques", la cartographie de ce groupe apparait systématiquement sur la carte du monde au lieu du polygone dessiné.

Cordialement, 

Vincent Lipa

**Comment by SiropOps** [comment]
Bonjour Vincent, je vois pas trop le problème ici. J'ai bien le polygone qui s'affiche ?

**Comment by SiropOps** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/56d56b5c-ee2c-4e58-93ad-8c88005385c5)

**Comment by Paris75012** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/74540524/2d28c69b-19b4-45a3-92ba-de637b91bb06)

**Comment by Paris75012** [comment]
Bonjour Cyril, 
la carte du monde répliquée s'affiche en premier. Il faut zoomer successivement afin de faire apparaître l'emplacement ou le groupe  détaillé.

Bien à toi, 
Vincent Lipa

**Comment by SiropOps** [comment]
Bonjour,

le problème n'est pas clairement identifiable, car non reproductible chez moi. J'ai changé un processus, Je te propose de ré ouvrir un ticket si cela ne fonctionne toujours pas.

bien à toi, Cyril
