### ISSUE TITLE
[LOC] BOTA-SC : Affichage de la cartographie

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1286]
Url : https://jbp.botalista.community/#/location/view/6234?tab=2
Username : paris

Description : Bonjour Cyril, 

J'obtiens le message ci-dessous : 

keycloak.computaceae-it.tech est bloqué

keycloak.computaceae-it.tech n'autorise pas la connexion

Bien à toi 
Vincent Lipa

**Comment by SiropOps** [comment]
Hello Vincent, Tu peux me mettre une capture d'écran ? Quelle navigateur ? Firefox ? Si oui, peut-tu faire CTRL+F5 sur https://jbp.botalista.community/#/location/view/6234?tab=2 puis de nouveau CTRL+F5 sur https://jbp.botalista.community/v2/ et me dire si ça fonctionne toujours pas. Merci
