### ISSUE TITLE
[CLV] création collecfif erreur

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1290]
Url : https://neu.botalista.community/v2/fr/collective/edit
Username : maire

Description : Salut,
Je veux créer un collectif, (pas en mode automatique, ca j'ai pas réussi à utiliser), je mets mes trois personnes, je clique sur sauvegarder, et ca met un message comme quoi le collectif est erroné. Pourtant je ne vois pas ce que j'aurais fait faux.
merci !

**Comment by al-maire** [comment]
![collectif](https://github.com/Computaceae-IT/cit-ticketing/assets/74531240/6bf0eb2f-9060-43dc-8bf3-6bbfc079328e)

j'ai pensé que peut être à caus que 2 personnes nônt pas d'initiales, mais j'ai essayé avec un autre colelctfi et ca ne marche pas non plus.
Merci

**Comment by SiropOps** [comment]
J'ai corrigé, il s'agissait d'un bug. ;-) Bien à toi

**Comment by al-maire** [comment]
Coucou,

J’ai pu créer un collectif, mais j’avais le message rouge « collectif erroné », donc j’ai pensé que ca marchait pas, et en voulant le refaire, j’ai eu le message qu’il existe déjà, et en effet, il a été crée

Merci,

Anne-Laure Maire

Jardin botanique de Neuchâtel
Charles-Knapp 33 | CH-2000 Neuchâtel
T : +41 (0)32 717 82 92
***@***.*** | www.jbneuchatel.ch

De : Cyril Boillat ***@***.***>
Envoyé : mardi, 15 août 2023 14:15
À : Computaceae-IT/cit-ticketing ***@***.***>
Cc : Maire Anne-Laure ***@***.***>; Comment ***@***.***>
Objet : Re: [Computaceae-IT/cit-ticketing] [CLV] création collecfif erreur (Issue #1290)

[E-MAIL EXTERNE]


J'ai corrigé, il s'agissait d'un bug. ;-) Bien à toi

**Comment by SiropOps** [comment]
Oui excuse, j'avais oublié de le supprimer ;-)Si tu as encore un soucis, fais moi signe.++Envoyé depuis mon téléphone ☎️ 
-------- Message d'origine --------De : al-maire ***@***.***> Date : 16.08.23  13:50  (GMT+01:00) À : Computaceae-IT/cit-ticketing ***@***.***> Cc : Cyril Boillat ***@***.***>, State change ***@***.***> Objet : Re: [Computaceae-IT/cit-ticketing] [CLV] création collecfif erreur (Issue #1290) 
Coucou,



J’ai pu créer un collectif, mais j’avais le message rouge « collectif erroné », donc j’ai pensé que ca marchait pas, et en voulant le refaire, j’ai eu le message qu’il existe déjà, et en effet, il a été crée



Merci,



Anne-Laure Maire



Jardin botanique de Neuchâtel

Charles-Knapp 33 | CH-2000 Neuchâtel

T : +41 (0)32 717 82 92

***@***.*** | www.jbneuchatel.ch



De : Cyril Boillat ***@***.***>

Envoyé : mardi, 15 août 2023 14:15

À : Computaceae-IT/cit-ticketing ***@***.***>

Cc : Maire Anne-Laure ***@***.***>; Comment ***@***.***>

Objet : Re: [Computaceae-IT/cit-ticketing] [CLV] création collecfif erreur (Issue #1290)



[E-MAIL EXTERNE]





J'ai corrigé, il s'agissait d'un bug. ;-) Bien à toi

**Comment by Paris75012** [comment]
Bonjour Cyril, 
 Je rencontre lea même anomalie. ll m'est impossbile de créer un nouveau collectif 
Bien à toi 
Vincent Lipa

**Comment by Paris75012** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/74540524/b02f1323-0526-4e60-a2ee-2034dd753af5)

**Comment by Paris75012** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/74540524/0a3eaf64-bfb3-40c9-8ce3-7f0a402afcba)

**Comment by SiropOps** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/756fe29e-8e04-4e55-bd89-be1aabc9c882)

**Comment by SiropOps** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/185bae7d-3e0a-4da3-aa99-c026f49008e5)

**Comment by SiropOps** [comment]
Hello Vincent, 
la construction du collectif doit toujours ce faire par, **NOM DE FAMILLE, I. & I. NOM DE FAMILLE** ou **NOM DE FAMILLE, I.** ou **NOM DE FAMILLE, I., I. NOM DE FAMILLE & I. NOM DE FAMILLE** etc...
Si on veut contourner cette logique, on peut désactiver la création automatique et sélecter les noms un par par, comme avant.

Bien à toi.

**Comment by Paris75012** [comment]
Bonjour Cyril,

Merci beaucoup pour ton retour.

Cordialement

Vincent Lipa

De : Cyril Boillat ***@***.***>
Envoyé : mardi 22 août 2023 19:54
À : Computaceae-IT/cit-ticketing ***@***.***>
Cc : Lipa, Vincent ***@***.***>; Comment ***@***.***>
Objet : Re: [Computaceae-IT/cit-ticketing] [CLV] création collecfif erreur (Issue #1290)

* Ce message a ete emis par un expediteur externe *
Prenez garde aux liens et aux pieces jointes. Ne fournissez jamais votre mot de passe de connexion Ville de Paris.

________________________________

Hello Vincent,
la construction du collectif doit toujours ce faire par, NOM DE FAMILLE, I. & I. NOM DE FAMILLE ou NOM DE FAMILLE, I. ou NOM DE FAMILLE, I., I. NOM DE FAMILLE & I. NOM DE FAMILLE etc...
Si on veut contourner cette logique, on peut désactiver la création automatique et sélecter les noms un par par, comme avant.

Bien à toi.
