### ISSUE TITLE
[ACQ] Blocage pour "Lier avec spécimen cultivé"

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1296]
Url : https://g.botalista.community/#/acquisition/view/68889
Error message : could not execute statement; SQL [n/a]; constraint [ind_number_unique]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Username : staehli

Description : Impossible de sauvegarder la fenêtre "Lier à un spécimen cultivé" (20171887J   Arenaria biflora). Pourtant tous les champs obligatoires sont remplis. Problème rencontré uniquement avec ce numéro.

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://g.botalista.community/api/cultivated/
Request method: POST
Status Code: 405 (Method Not Allowed)
Data send: 
 {"parent":{"idAcquisition":68889,"uid":"77f85f81-d535-4f26-ac28-0471e77a0c61","typeEntite":"J"},"areaRepartition":"Montagnes S. Europe\n","number":null,"goal":{"id":1,"name":"collection"},"sector":{"version":1,"key":"Rocailles","value":"Rocailles","idFunctionalUnit":4,"uid":"dba5e1f9-83b0-46c9-ad6a-9878fab97f9a","location":{"typeEntite":"Site","version":0,"idLocation":1,"uid":"3d7ff628-3de7-4c27-b7d2-1029bf90c843","name":"CJB","completeName":"CJB","code":"CJB"},"type":"enum_sector","name":"Rocailles","archive":false},"responsible":{"uid":"ca45e4bb-bf04-44a3-86c9-c412d967d771","forename":"Marilyn","surname":"Staehli","initial":"M."},"sex":null,"plate":{"responsible":null,"date":"2023-08-18","datePrecision":"day","simplePlateState":"enum_unknown","doublePlateState":"enum_missing"},"note":null,"oldLocations":[]}
 Error Type: com.botalista.lib.core.errors.container.CriticalError
Error message: 
 could not execute statement; SQL [n/a]; constraint [ind_number_unique]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by SiropOps** [comment]
C'est parce qu'il avait un SC rattaché au SA de type indexseminum. J'ai fais le changement et tout est bon.
