### ISSUE TITLE
[AUT] Impossible de modifier la citation d'auteur

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1298]
Url : https://ncy.botalista.community/v2/fr/authority/edit/id/4214
Username : beghoura

Description : Il m'est impossible de modifier la citation de l'auteur sur une espèce

**Comment by SiropOps** [comment]
Normal, c'est citation est lier à 1642 noms, tu ne peux pas la modifier, sans modifier tous ces noms. Pour modifier la citation d'un seul nom, faut aller dans l'édition du nom en question. par exemple https://ncy.botalista.community/#/nomenclature/edit/590452.

Attention, si le nom est un nom WFO, il n'est pas modifiable, il faut en recréer un.

![image](https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/0c5fc86c-cdf4-4149-8398-47bce3f333ed)

![image](https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/5f7bbbc1-e5f2-459b-9ba8-19ae3281b6ab)
