### ISSUE TITLE
[ACQ] Modifier l'année d'acquisition

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1302]
Url : https://ncy.botalista.community/#/acquisition/edit/31438
Username : beghoura

Description : Après erreur, je souhaite modifier l'année d'acquisition.

**Comment by SiropOps** [comment]
C'est tout a fait possible, cela va juste pas modifier le numéro d'acquisition Botalista, comme demandé #1299
