### ISSUE TITLE
[FUN] unité fonctionnelle : Pavillons & Pavillons (ex-tacot) dans les secteurs actifs

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1303]
Url : https://jbp.botalista.community/#/functionalunit/list/
Username : paris

Description : Bonjour Cyril, 
Nous avons bien le secteur Pavillons dans la recherche des unités fonctionnelles. Or celui-ci n'apparait pas dans la liste des secteurs actifs.

Nous avons 'Pavillons (ex-tacot) au lieu de Pavillons. 

De plus, j'ai essayé de modifier le secteur du SC 20220519HO (Pogostemon cablin) de 'Pôle serres' à 'Pavillons'. Le système indique 'Permissions insuffisantes'

Bien à toi, 
VIncent Lipa

**Comment by SiropOps** [comment]
C'est modifié et appliqué sur le profil paris. A ajouter sur les autres profils, le cas échéant.

Bien à toi.

Cyril
