### ISSUE TITLE
[NOM] Modification nomenclaturale

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1306]
Url : https://ncy.botalista.community/#/nomenclature/view/1605525?tab=2
Username : beghoura

Description : Salut Cyril,

Alors voilà, WFO n'est pas forcément à jour d'un point de vue nomenclaturale. Tu dois parfois faire de petites modifs, surtout inhérentes au nom de l'auteur. 
Le problème, c'est que quand c'est un taxon WFO, tu ne peux pas. 

Donc je crée un nouveau nom avec la bonne nomenclature et je le rajoute en synonyme. Là, ça marche... parfois. 

Si je le rattache à un nom sans synonymes, aucuns soucis. 
Si je le rattache à un nom avec des synonymes, c'est impossible. Je dois alors supprimer les synonymes du nom pour pouvoir le rattacher et ça, c'est pas possible en fait. 

Quelles sont les solutions envisageables!?

**Comment by SiropOps** [comment]
Le réponse au ticket #1307
