### ISSUE TITLE
[NOM] Forcé l'acceptation du point de vue WFO

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1307]
Url : https://ncy.botalista.community/#/nomenclature/view/1183125?tab=1
Username : beghoura

Description : Est-on réellement obligé de créer un nouveau nom pour pousser un taxon WFO à être accepté?

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/efe4258f-a172-418d-bda3-9e48a43ef1b5
