### ISSUE TITLE
[S.L] Bota-nom : année obtention differente entre la fiche nom et l'export

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1316]
Url : https://jbp.botalista.community/#/
Username : paris

Description : Bonjour les DEV de Botalista, 
Nous rencontrons l'anomalie suivante : 
Iris x germanica Louise Auréo
Fiche nom plante : année obtrntion  1947 (modifié ce matin) et export excel des SC ( année obtention 1946)

La bonne date est 1947.

Bien à toi, 
Vincent Lipa

**Comment by Paris75012** [comment]
Louise Auréau : correction du nom du cultivar

**Comment by SiropOps** [comment]
Hello Vincent, j'ai bien 1947, sur les export SC (voir ci-joint) ?

**Comment by SiropOps** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/aa3412f7-5d59-4b12-8f37-34b862354d2f)

**Comment by Paris75012** [comment]
Bonjour Cyril,

Merci beaucoup !!
J'ai une question : les valeurs ou données corrigées  apparaissent-elles seulement  le lendemain de la modification, à titre d'exemple l'année d'obtention ici, sur l'exportation Excel des SC ou noms de Botalista  ?

Bien à toi,
Vincent Lipa


-------- Message d'origine --------
De : Cyril Boillat ***@***.***>
Date : 19/09/2023 18:47 (GMT+01:00)
À : Computaceae-IT/cit-ticketing ***@***.***>
Cc : "Lipa, Vincent" ***@***.***>, Comment ***@***.***>
Objet : Re: [Computaceae-IT/cit-ticketing] [S.L] Bota-nom : année obtention differente entre la fiche nom et l'export (Issue #1316)

* Ce message a ete emis par un expediteur externe *
Prenez garde aux liens et aux pieces jointes. Ne fournissez jamais votre mot de passe de connexion Ville de Paris.

________________________________

[image]<https://user-images.githubusercontent.com/35902374/269033832-aa3412f7-5d59-4b12-8f37-34b862354d2f.png>

**Comment by SiropOps** [comment]
Bonjour Vincent, normalement toutes les modifications sont synchrones; c'est à dire que la modification d'un nom à une récupération direct sur les spécimens. Mais, il est vrai que lors d'un problème de synchronisation, une copie complète des données est faite chaque nuit. Ce qui explique que certaines données peuvent être mise à jour la nuit suivante.

Bien à toi
