### ISSUE TITLE
[ACQ] Soucis pour forcer un nom qui est un synonyme pour WFO

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1319]
Url : https://ncy.botalista.community/#/acquisition/edit/
Username : berthold

Description : Salut Cyril,

J'ai un soucis sur la base noms qu'impacte mes inventaires. J'ai une Drosera gracilis Hook.f. ex Planch. qui reste un débat taxonomique entre D. gracilis et D. peltata Thunb. J'ai décidé de garder D. gracilis chez nous pour l'instant et j'ai mis "ignoré" dans le statut du nom. Le problème c'est que la base des noms me force toujours D. peltata dans le nom accepté quand j'essaye de faire l'acquisition de ce taxon. C'est un bug ou faut t'il "forcer" d'une autre façon?

Merci d'avance
Carl

**Comment by SiropOps** [comment]
A priori, non. Quand tu mets ignoré dans le status du nom, c'est justement que tu veux l'ignorer; donc plus l'utiliser. Dans ton cas il fallait juste l'accepter. Je te mets une capture d'écran joins.

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/b83a1a2f-da54-4767-9d57-62ea9beae844

**Comment by Carl-Berthold** [comment]
Salut Cyril,

Corrige-moi si je comprends mal mais la solution proposé dans ton vidéo va faire que Drosera peltata est synonyme de D. gracilis. Pour l'instant je dois garder les deux en accepté car les deux existe depuis longtemps. C'est juste que Drosera peltata est un complexe qui est en train de agglomérer plein d'autres taxons et les rendre synonyme.

**Comment by SiropOps** [comment]
Excuse j'avais pas compris ça. Désolé. Je corrige ;-)
++
