### ISSUE TITLE
[REC] changement dans collecteur pas sivibée dans les acquisitions

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1329]
Url : https://neu.botalista.community/#/harvest/view/587?tab=1
Username : maire

Description : Bug ?
Quand je change un collectif de personne après avoir saisi une récolte et des acquisitions liées, le changement ne semble pas se répercuter sur les données liées à l'acquisition, par exemple si je fais une export, ou dans les données consultables avec l'acquisition.
Est-ce que le changement se répercute quand même dans la base de données, mais pas dans les informations consultables ? je ne trouve pas idéal, car on ne sait pas si le changement a fonctionné ou non.

**Comment by SiropOps** [comment]
Hello Anne-Laure,
la mise à jour à lieu chaque nuit, ce n'est pas idéal mais ça va changer avec le nouveau module des récoltes.
