### ISSUE TITLE
[CULT] Impossible d'imprimer les étiquettes

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1332]
Url : https://bord.botalista.community/#/cultivated/list/?filters=%7B%22type%22:%22selector%22,%22key%22:%22number%22%7D
Username : barthou

Description : Impossible d'imprimer les étiquettes car je n'ai pas l'arbre dans le processus.

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/7c6ed66d-86aa-4ba1-a397-1e1dbb9819c6
