### ISSUE TITLE
[lot] BOTA-ISE : Génération de l'ISE de Paris 

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1334]
Url : https://jbp.botalista.community/v2/fr/lot/list
Username : paris

Description : Bonjour Cyril, 
Je souhaiterai générer mon ISE depuis BOTALISTA. J'ai effectué une sélection des lots des années 2019 à 2023 depuis BOTA-IS  (lots de graine). Je me suis rendu dans l'onglet Index Seminum. Il n'apparait aucun lot sélectionné pour l'IS. Comment puis-je faire pour les faire apparaitre dans BOTA-IS (Index seminum) ?

Ps : J'ai revisionné l'excellente vidéo Botalista Wiki du 12/2022.
Bien à toi 
VIncent Lipa

**Comment by Paris75012** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/74540524/3ac5d24b-2357-4680-80b8-ac7810cc0c15)

**Comment by Paris75012** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/74540524/9494810a-68a4-45cb-aa91-24f2afab2f40)

**Comment by Paris75012** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/74540524/e36a813c-5285-4e18-8c7e-9a94dd367267)

**Comment by Paris75012** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/74540524/f69ee42a-b4c4-4d18-b94f-8d9d430038fa)

**Comment by SiropOps** [comment]
C'était un bug, désolé. Les données seront à jour dans la matinée. Bien à toi, Cyril

**Comment by Paris75012** [comment]
Merci beaucoup ! :)
Bien à toi,

**Comment by Paris75012** [comment]
Vincent
