### ISSUE TITLE
[ACQ] Je n'arrive pas à créer une acquisition

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1335]
Url : https://ncy.botalista.community/#/acquisition/edit/
Username : berthold

Description : Salut Cyril,
J'espère que tu vas bien?
Je n'arrive pas à créer l'acquisition 20233297 car il me dit que il existe déjà une acquisition avec ses mêmes donnés. J'ai regardé avec notre ACCID et l'IPEN et je ne trouve rien. J'ai surement raté quelque chose mais je ne sais pas quoi...
Merci d'avance pour ton aide
Carl

**Comment by Carl-Berthold** [comment]
Le message d'erreur précis est:
"Il existe un enregistrement avec les mêmes propriétés"

**Comment by SiropOps** [comment]
Ok, ça vient du faite que j'ai changer la date d'acqusition du :
https://ncy.botalista.community/#/acquisition/view/31473
de 2023 a 2017, ça fout la merde.... Je l'ai repassé à 2023. Il faudrait le supprimer et le recréer ?

**Comment by Carl-Berthold** [comment]
Ah mince, Ok supprime tout et je refais les deux comme il faut cette fois-ci
Merci et bon weekend!
