### ISSUE TITLE
[NOM] nom bloqué sur un synonyme qui n'en fait pas partie

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1352]
Url : https://g.botalista.community/#/nomenclature/view/226579
Username : buchschacher

Description : Impossible de dissocier ce nom qui est une vraie sous-espèce et non pas un synonyme: voici ce que dis WFO: Astragalus monspessulanus subsp. monspessulanus 

     

    This name is the accepted name of an infraspecific taxon of the species Astragalus monspessulanus L. in the genus Astragalus (family Fabaceae).

    The record derives from ILDIS (data supplied on 2023-02-24) which reports it as an accepted name

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/ae85b60a-9385-4d80-98bb-514bdb31f21e
