### ISSUE TITLE
[NOM] BOTA-NOM : modification genre Dahlia

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1356]
Url : https://jbp.botalista.community/#/nomenclature/edit/446712
Username : paris

Description : Bonjour Cyril, 

je rencontre une anomalie sur les noms de cultivars de Dahlia. Ceux-ci sont rattachés au nom de genre Dahlia Thunb.. Il s'agit d'un synonyme de Trichocladus Pers.Selon quelle procedure, puis-je attribuer le bon nom de genre (ici Dahlia cav.) à plus de 300  cultivars de Dahlia ?

Je te remercie par avance pour ton aide.

Bien à toi, 

VIncent Lipa

**Comment by SiropOps** [comment]
Bonjour Vincent, il n'y pas, malheureusement, de possibilité automatique. Je te propose, tu me donnes la liste des cultivars, sous Excel à modifier, et je te fais la modification directement en base de données ?

Bien à toi, Cyril

**Comment by Paris75012** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/lipav/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/lipav/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<title>Untitled Spreadsheet</title>
<style>

</style>
</head>

<body link=blue vlink=purple>



Nom d'acquisition | Détermination nécessaire | Famille | Genre | Espèce | Sous-espèce | Cultivar
-- | -- | -- | -- | -- | -- | --
Dahlia Thunb.  'Michele Mignot' |   | Hamamelidaceae | Dahlia |   |   | Michele Mignot
Dahlia Thunb.  'Colvil' |   | Hamamelidaceae | Dahlia |   |   | Colvil
Dahlia Thunb.  'Café au Lait Royal' |   | Hamamelidaceae | Dahlia |   |   | Café au Lait Royal
Dahlia Thunb.  'Andre Dognin' |   | Hamamelidaceae | Dahlia |   |   | Andre Dognin
Dahlia Thunb.  'Nescio' |   | Hamamelidaceae | Dahlia |   |   | Nescio
Dahlia Thunb.  'Gold Crown' |   | Hamamelidaceae | Dahlia |   |   | Gold Crown
Dahlia Thunb.  'Alfred Grille' |   | Hamamelidaceae | Dahlia |   |   | Alfred Grille
Dahlia coccinea    IB 52 |   | Asteraceae | Dahlia | coccinea |   | IB 52
Dahlia merckii    HI 7103 |   | Asteraceae | Dahlia | merckii |   | HI 7103
Dahlia coccinea    IB 7000 |   | Asteraceae | Dahlia | coccinea |   | IB 7000
Dahlia Thunb.  'Marisel Amoroso' |   | Hamamelidaceae | Dahlia |   |   | Marisel Amoroso
Dahlia Thunb.  'Honka' |   | Hamamelidaceae | Dahlia |   |   | Honka
Dahlia Thunb.  'Little Robert' |   | Hamamelidaceae | Dahlia |   |   | Little Robert
Dahlia Thunb.  'Samuel' |   | Hamamelidaceae | Dahlia |   |   | Samuel
Dahlia Thunb.  'Black Jack' |   | Hamamelidaceae | Dahlia |   |   | Black Jack
Dahlia Thunb.  'Harry Bo' |   | Hamamelidaceae | Dahlia |   |   | Harry Bo
Dahlia Thunb.  'Prestige' |   | Hamamelidaceae | Dahlia |   |   | Prestige
Dahlia Thunb.  'Charming Lady' |   | Hamamelidaceae | Dahlia |   |   | Charming Lady
Dahlia Thunb.  'Verrone's Obsidian' |   | Hamamelidaceae | Dahlia |   |   | Verrone's Obsidian
Dahlia Thunb.  'Floralies d'Orléans' |   | Hamamelidaceae | Dahlia |   |   | Floralies d'Orléans
Dahlia Thunb.  'Pinelands Princess' |   | Hamamelidaceae | Dahlia |   |   | Pinelands Princess
Dahlia Thunb.  'Alfred Lorenzen' |   | Hamamelidaceae | Dahlia |   |   | Alfred Lorenzen
Dahlia Thunb.  'Mamie N°13' |   | Hamamelidaceae | Dahlia |   |   | Mamie N°13
Dahlia Thunb.  'Yellow Passion' |   | Hamamelidaceae | Dahlia |   |   | Yellow Passion
Dahlia Thunb.  'Totally Tangerine' |   | Hamamelidaceae | Dahlia |   |   | Totally Tangerine
Dahlia Thunb.  'Yohkoh' |   | Hamamelidaceae | Dahlia |   |   | Yohkoh
Dahlia Thunb.  'Genova' |   | Hamamelidaceae | Dahlia |   |   | Genova
Dahlia Thunb.  'Wowie' |   | Hamamelidaceae | Dahlia |   |   | Wowie
Dahlia Thunb.  'Jowey Rita' |   | Hamamelidaceae | Dahlia |   |   | Jowey Rita
Dahlia Thunb.  'Claire de Lune' |   | Hamamelidaceae | Dahlia |   |   | Claire de Lune
Dahlia Thunb.  'Nuit d'Eté' |   | Hamamelidaceae | Dahlia |   |   | Nuit d'Eté
Dahlia Thunb.  'Hy Halo' |   | Hamamelidaceae | Dahlia |   |   | Hy Halo
Dahlia Thunb.  'Emory Paul' |   | Hamamelidaceae | Dahlia |   |   | Emory Paul
Dahlia Thunb.  'Night Butterfly' |   | Hamamelidaceae | Dahlia |   |   | Night Butterfly
Dahlia Thunb.  'Schloss Reinbek' |   | Hamamelidaceae | Dahlia |   |   | Schloss Reinbek
Dahlia Thunb.  'Eclatant' |   | Hamamelidaceae | Dahlia |   |   | Eclatant
Dahlia Thunb.  'Etoile des neiges' |   | Hamamelidaceae | Dahlia |   |   | Etoile des neiges
Dahlia Thunb.  'Bettina Verbeek' |   | Hamamelidaceae | Dahlia |   |   | Bettina Verbeek
Dahlia merckii    H    7079 |   | Asteraceae | Dahlia | merckii |   | H  7079
Dahlia Thunb.  'Christie Dancer' |   | Hamamelidaceae | Dahlia |   |   | Christie Dancer
Dahlia Thunb.  'Mas Cory' |   | Hamamelidaceae | Dahlia |   |   | Mas Cory
Dahlia Thunb.  'Shea's Rainbow' |   | Hamamelidaceae | Dahlia |   |   | Shea's Rainbow
Dahlia Thunb.  'Frigoulet' |   | Hamamelidaceae | Dahlia |   |   | Frigoulet
Dahlia Thunb.  'Rose des Sables®' |   | Hamamelidaceae | Dahlia |   |   | Rose des Sables®
Dahlia Thunb.  'Mulhouse Zoo' |   | Hamamelidaceae | Dahlia |   |   | Mulhouse Zoo
Dahlia Cav.  'Bel Amour' |   | Asteraceae | Dahlia |   |   | Bel Amour
Dahlia Thunb.  'Innocence' |   | Hamamelidaceae | Dahlia |   |   | Innocence
Dahlia Thunb.  'Bumble Rumble' |   | Hamamelidaceae | Dahlia |   |   | Bumble Rumble
Dahlia Thunb.  'Rebecca's World' |   | Hamamelidaceae | Dahlia |   |   | Rebecca's World
Dahlia Thunb.  'Jess Sarah' |   | Hamamelidaceae | Dahlia |   |   | Jess Sarah
Dahlia   Thunb.  'Etoile digoinaise blanche' | Hamamelidaceae | Dahlia |   |   | Etoile digoinaise blanche
Dahlia Thunb.  'Feu du Soleil' |   | Hamamelidaceae | Dahlia |   |   | Feu du Soleil
Dahlia Thunb.  'Optic Illusion' |   | Hamamelidaceae | Dahlia |   |   | Optic Illusion
Dahlia Thunb. 'Mystic Ladies Scarlet' |   | Hamamelidaceae | Dahlia |   |   | Mystic Ladies Scarlet
Dahlia Thunb.  'Feu Follet' |   | Hamamelidaceae | Dahlia |   |   | Feu Follet
Dahlia Thunb.  'Rundale' |   | Hamamelidaceae | Dahlia |   |   | Rundale
Dahlia Thunb.  'Union Jack' |   | Hamamelidaceae | Dahlia |   |   | Union Jack
Dahlia Thunb.  'Cherry Star' |   | Hamamelidaceae | Dahlia |   |   | Cherry Star
Dahlia merckii    05.2536 |   | Asteraceae | Dahlia | merckii |   | 05.2536
Dahlia Thunb. 'Charles de Gaulle' |   | Hamamelidaceae | Dahlia |   |   | Charles de Gaulle
Dahlia Thunb.  'Aranka' |   | Hamamelidaceae | Dahlia |   |   | Aranka
Dahlia Thunb.  'Platinum Blonde' |   | Hamamelidaceae | Dahlia |   |   | Platinum Blonde
Dahlia Thunb.  'Route du dahlia' |   | Hamamelidaceae | Dahlia |   |   | Route du dahlia
Dahlia Thunb.  'Dark Diamond' |   | Hamamelidaceae | Dahlia |   |   | Dark Diamond
Dahlia Thunb.  'Deuil du Roi Albert' |   | Hamamelidaceae | Dahlia |   |   | Deuil du Roi Albert
Dahlia Thunb.  'Vasco jaune' |   | Hamamelidaceae | Dahlia |   |   | Vasco jaune
Dahlia Thunb.  'Clown' |   | Hamamelidaceae | Dahlia |   |   | Clown
Dahlia   Thunb. 'Château D'Urville / Deldajor' | Hamamelidaceae | Dahlia |   |   | Château D'Urville / Deldajor
Dahlia Thunb.  'Huguette Saison' |   | Hamamelidaceae | Dahlia |   |   | Huguette Saison
Dahlia Thunb.  'Teesbrooke Audrey' |   | Hamamelidaceae | Dahlia |   |   | Teesbrooke Audrey
Dahlia Thunb.  'David Howard' |   | Hamamelidaceae | Dahlia |   |   | David Howard
Dahlia Thunb.  'Nadezda' |   | Hamamelidaceae | Dahlia |   |   | Nadezda
Dahlia Thunb.  'Valentino' |   | Hamamelidaceae | Dahlia |   |   | Valentino
Dahlia Thunb.  'Zifen Shuang' |   | Hamamelidaceae | Dahlia |   |   | Zifen Shuang
Dahlia Thunb.  'Samantha' |   | Hamamelidaceae | Dahlia |   |   | Samantha
Dahlia Thunb.  'Alpen Pauline' |   | Hamamelidaceae | Dahlia |   |   | Alpen Pauline
Dahlia Thunb.  'Pashmina' |   | Hamamelidaceae | Dahlia |   |   | Pashmina
Dahlia Thunb.  'Kenora Macop' |   | Hamamelidaceae | Dahlia |   |   | Kenora Macop
Dahlia Thunb.  'Ingrid' |   | Hamamelidaceae | Dahlia |   |   | Ingrid
Dahlia   Thunb.  'Château de la Bourdaisière' | Hamamelidaceae | Dahlia |   |   | Château de la Bourdaisière
Dahlia Thunb.  'Bishop of Llandaff' |   | Hamamelidaceae | Dahlia |   |   | Bishop of Llandaff
Dahlia Thunb.  'Normandie' |   | Hamamelidaceae | Dahlia |   |   | Normandie
Dahlia Thunb.  'Chat Noir' |   | Hamamelidaceae | Dahlia |   |   | Chat Noir
Dahlia Thunb.  'Perfect' |   | Hamamelidaceae | Dahlia |   |   | Perfect
Dahlia Thunb.  'Aumonier Chandelon' |   | Hamamelidaceae | Dahlia |   |   | Aumonier Chandelon
Dahlia Thunb.  'Fatima' |   | Hamamelidaceae | Dahlia |   |   | Fatima
Dahlia Thunb.  'Spartacus' |   | Hamamelidaceae | Dahlia |   |   | Spartacus
Dahlia Thunb. 'Candy Eyes' |   | Hamamelidaceae | Dahlia |   |   | Candy Eyes
Dahlia Thunb.  'Roma' |   | Hamamelidaceae | Dahlia |   |   | Roma
Dahlia Thunb.  'Dark Fubuki' |   | Hamamelidaceae | Dahlia |   |   | Dark Fubuki
Dahlia Thunb.  'Eveline' |   | Hamamelidaceae | Dahlia |   |   | Eveline
Dahlia Thunb.  'Pampa' |   | Hamamelidaceae | Dahlia |   |   | Pampa
Dahlia Thunb.  'Painted Girl' |   | Hamamelidaceae | Dahlia |   |   | Painted Girl
Dahlia Thunb.  'Arabian Night' |   | Hamamelidaceae | Dahlia |   |   | Arabian Night
Dahlia Thunb.  'Apelsini Sniega' |   | Hamamelidaceae | Dahlia |   |   | Apelsini Sniega
Dahlia Thunb.  'Bright and Black' |   | Hamamelidaceae | Dahlia |   |   | Bright and Black
Dahlia Thunb.  'Alauna Chamade' |   | Hamamelidaceae | Dahlia |   |   | Alauna Chamade
Dahlia Thunb.  'Cha Cha' |   | Hamamelidaceae | Dahlia |   |   | Cha Cha
Dahlia Thunb.  'Willi Jason' |   | Hamamelidaceae | Dahlia |   |   | Willi Jason
Dahlia Thunb.  'Dina' |   | Hamamelidaceae | Dahlia |   |   | Dina
Dahlia Thunb. 'Cebu' |   | Hamamelidaceae | Dahlia |   |   | Cebu
Dahlia Thunb.  'Fancy' |   | Hamamelidaceae | Dahlia |   |   | Fancy
Dahlia Thunb.  'G.F. Hemerick' |   | Hamamelidaceae | Dahlia |   |   | G.F. Hemerick
Dahlia Thunb.  'Jess - Carol' |   | Hamamelidaceae | Dahlia |   |   | Jess - Carol
Dahlia Thunb.  'Mme Frissard' |   | Hamamelidaceae | Dahlia |   |   | Mme Frissard
Dahlia Thunb.  'Piuku' |   | Hamamelidaceae | Dahlia |   |   | Piuku
Dahlia Thunb.  'Roi du midi' |   | Hamamelidaceae | Dahlia |   |   | Roi du midi
Dahlia Thunb.  'Happy Single Party' |   | Hamamelidaceae | Dahlia |   |   | Happy Single Party
Dahlia Thunb.  'Parc floral de Paris' |   | Hamamelidaceae | Dahlia |   |   | Parc floral de Paris
Dahlia Thunb.  'Gitts Attention' |   | Hamamelidaceae | Dahlia |   |   | Gitts Attention
Dahlia Thunb.  'Television' |   | Hamamelidaceae | Dahlia |   |   | Television
Dahlia Thunb.  'La vie en rose' |   | Hamamelidaceae | Dahlia |   |   | La vie en rose
Dahlia Thunb.  'Otto's Thrill' |   | Hamamelidaceae | Dahlia |   |   | Otto's Thrill
Dahlia Thunb.  'Mayan Fancy' |   | Hamamelidaceae | Dahlia |   |   | Mayan Fancy
Dahlia Thunb.  'Jours de France' |   | Hamamelidaceae | Dahlia |   |   | Jours de France
Dahlia Thunb.  'Bangkok Violet' |   | Hamamelidaceae | Dahlia |   |   | Bangkok Violet
Dahlia Thunb.  'Poésie' |   | Hamamelidaceae | Dahlia |   |   | Poésie
Dahlia Thunb.  'Lisonette' |   | Hamamelidaceae | Dahlia |   |   | Lisonette
Dahlia Thunb.  'Nonette' |   | Hamamelidaceae | Dahlia |   |   | Nonette
Dahlia Thunb.  'Nirvana' |   | Hamamelidaceae | Dahlia |   |   | Nirvana
Dahlia Thunb.  'À la folie' |   | Hamamelidaceae | Dahlia |   |   | À la folie
Dahlia Thunb.  'Gerrie Hoek' |   | Hamamelidaceae | Dahlia |   |   | Gerrie Hoek
Dahlia Thunb.  'Mystère' |   | Hamamelidaceae | Dahlia |   |   | Mystère
Dahlia Thunb.  'Veritable' |   | Hamamelidaceae | Dahlia |   |   | Veritable
Dahlia Thunb.  'Mas Marie 2' |   | Hamamelidaceae | Dahlia |   |   | Mas Marie 2
Dahlia Thunb.  'Isadora' |   | Hamamelidaceae | Dahlia |   |   | Isadora
Dahlia Thunb.  'Izarra' |   | Hamamelidaceae | Dahlia |   |   | Izarra
Dahlia Thunb.  'Vasco rose' |   | Hamamelidaceae | Dahlia |   |   | Vasco rose
Dahlia Thunb.  'Mistral' |   | Hamamelidaceae | Dahlia |   |   | Mistral
Dahlia Thunb. 'Mystic Ladies Haze' |   | Hamamelidaceae | Dahlia |   |   | Mystic Ladies Haze
Dahlia Thunb.  'Giggles' |   | Hamamelidaceae | Dahlia |   |   | Giggles
Dahlia Thunb.  'Jowey Nicky' |   | Hamamelidaceae | Dahlia |   |   | Jowey Nicky
Dahlia Thunb.  'Christie Red' |   | Hamamelidaceae | Dahlia |   |   | Christie Red
Dahlia Thunb.  'Zhemchzhinka' |   | Hamamelidaceae | Dahlia |   |   | Zhemchzhinka
Dahlia Thunb.  'Mexican black' |   | Hamamelidaceae | Dahlia |   |   | Mexican black
Dahlia Thunb.  'Mistigris' |   | Hamamelidaceae | Dahlia |   |   | Mistigris
Dahlia Thunb.  'Windmill' |   | Hamamelidaceae | Dahlia |   |   | Windmill
Dahlia   Thunb.  'Arboretum du prés des Culants' | Hamamelidaceae | Dahlia |   |   | Arboretum du prés des Culants
Dahlia Thunb.  'Elma Elizabeth' |   | Hamamelidaceae | Dahlia |   |   | Elma Elizabeth
Dahlia Thunb.  'Elektra' |   | Hamamelidaceae | Dahlia |   |   | Elektra
Dahlia   Thunb. 'Mystic Ladies World Smith' | Hamamelidaceae | Dahlia |   |   | Mystic Ladies World Smith
Dahlia Thunb.  'Sheila' |   | Hamamelidaceae | Dahlia |   |   | Sheila
Dahlia Thunb.  'Klankstad Kerkrade' |   | Hamamelidaceae | Dahlia |   |   | Klankstad Kerkrade
Dahlia Thunb.  'Miss Rose Fletcher' |   | Hamamelidaceae | Dahlia |   |   | Miss Rose Fletcher
Dahlia Thunb.  'Cabana Banana' |   | Hamamelidaceae | Dahlia |   |   | Cabana Banana
Dahlia Thunb.  'Myrtle's Folly' |   | Hamamelidaceae | Dahlia |   |   | Myrtle's Folly
Dahlia Thunb.  'Denise Audouard' |   | Hamamelidaceae | Dahlia |   |   | Denise Audouard
Dahlia Thunb.  'Melody Allegro' |   | Hamamelidaceae | Dahlia |   |   | Melody Allegro
Dahlia Thunb.  'Aloha' |   | Hamamelidaceae | Dahlia |   |   | Aloha
Dahlia Thunb.  'Edinburgh' |   | Hamamelidaceae | Dahlia |   |   | Edinburgh
Dahlia Thunb.  'Bel Amour' |   | Hamamelidaceae | Dahlia |   |   | Bel Amour
Dahlia Thunb.  'Emmaüs' |   | Hamamelidaceae | Dahlia |   |   | Emmaüs
Dahlia Thunb.  'Franz Kafka' |   | Hamamelidaceae | Dahlia |   |   | Franz Kafka
Dahlia Thunb.  'Caméléon' |   | Hamamelidaceae | Dahlia |   |   | Caméléon
Dahlia Thunb.  'Mme Labruyère' |   | Hamamelidaceae | Dahlia |   |   | Mme Labruyère
Dahlia Thunb.  'Willi Lorenzo' |   | Hamamelidaceae | Dahlia |   |   | Willi Lorenzo
Dahlia Thunb.  'Karma Lagoon' |   | Hamamelidaceae | Dahlia |   |   | Karma Lagoon
Dahlia Thunb.  'COLFI' |   | Hamamelidaceae | Dahlia |   |   | COLFI
Dahlia Thunb.  'Irena' |   | Hamamelidaceae | Dahlia |   |   | Irena
Dahlia Thunb.  'Rimbaud' |   | Hamamelidaceae | Dahlia |   |   | Rimbaud
Dahlia Thunb.  'Héroïne' |   | Hamamelidaceae | Dahlia |   |   | Héroïne
Dahlia Thunb.  'Etoile Digoinaise' |   | Hamamelidaceae | Dahlia |   |   | Etoile Digoinaise
Dahlia Thunb.  'Lilac Time' |   | Hamamelidaceae | Dahlia |   |   | Lilac Time
Dahlia Thunb.  'Malabar' |   | Hamamelidaceae | Dahlia |   |   | Malabar
Dahlia Thunb.  'Ruban Rose' |   | Hamamelidaceae | Dahlia |   |   | Ruban Rose
Dahlia Thunb.  'Gallery Valentin' |   | Hamamelidaceae | Dahlia |   |   | Gallery Valentin
Dahlia Thunb.  'Edna C' |   | Hamamelidaceae | Dahlia |   |   | Edna C
Dahlia Thunb.  'Stefanie Hertel' |   | Hamamelidaceae | Dahlia |   |   | Stefanie Hertel
Dahlia Thunb.  'Bonne Espérance' |   | Hamamelidaceae | Dahlia |   |   | Bonne Espérance
Dahlia Thunb.  'Ben Huston' |   | Hamamelidaceae | Dahlia |   |   | Ben Huston
Dahlia Thunb.  'Montreuil' |   | Hamamelidaceae | Dahlia |   |   | Montreuil
Dahlia   Thunb.  'Etoile digoinaise Rouge' | Hamamelidaceae | Dahlia |   |   | Etoile digoinaise Rouge
Dahlia Thunb.  'Anka' |   | Hamamelidaceae | Dahlia |   |   | Anka
Dahlia Thunb.  'Jowey Antibes' |   | Hamamelidaceae | Dahlia |   |   | Jowey Antibes
Dahlia Thunb.  'Classic Rosamunde' |   | Hamamelidaceae | Dahlia |   |   | Classic Rosamunde
Dahlia Thunb.  'Kaiser Wilhelm' |   | Hamamelidaceae | Dahlia |   |   | Kaiser Wilhelm
Dahlia Thunb.  'Raisa' |   | Hamamelidaceae | Dahlia |   |   | Raisa
Dahlia Thunb.  'Hapet Vino' |   | Hamamelidaceae | Dahlia |   |   | Hapet Vino
Dahlia Thunb.  'Les Sables d’Olonne' |   | Hamamelidaceae | Dahlia |   |   | Les Sables d’Olonne
Dahlia Thunb.  'Pooh' |   | Hamamelidaceae | Dahlia |   |   | Pooh
Dahlia Thunb.  'Honka Rood' |   | Hamamelidaceae | Dahlia |   |   | Honka Rood
Dahlia Thunb.  'Gloire de paris' |   | Hamamelidaceae | Dahlia |   |   | Gloire de paris
Dahlia   Thunb. 'Mystic Ladies® Knock Out' | Hamamelidaceae | Dahlia |   |   | Mystic Ladies® Knock Out
Dahlia Thunb.  'Contraste' |   | Hamamelidaceae | Dahlia |   |   | Contraste
Dahlia Thunb.  'Mandanera' |   | Hamamelidaceae | Dahlia |   |   | Mandanera
Dahlia Thunb.  'Jowey Shana' |   | Hamamelidaceae | Dahlia |   |   | Jowey Shana
Dahlia Thunb.  'Café Au Lait' |   | Hamamelidaceae | Dahlia |   |   | Café Au Lait
Dahlia Thunb.  'Gallery Singer' |   | Hamamelidaceae | Dahlia |   |   | Gallery Singer
Dahlia Thunb.  'Magic Moment' |   | Hamamelidaceae | Dahlia |   |   | Magic Moment
Dahlia Thunb.  'Pennsgift' |   | Hamamelidaceae | Dahlia |   |   | Pennsgift
Dahlia Thunb.  'Rocquencourt' |   | Hamamelidaceae | Dahlia |   |   | Rocquencourt
Dahlia Thunb. 'Nenekazi' |   | Hamamelidaceae | Dahlia |   |   | Nenekazi
Dahlia Thunb.  'Virtuose' |   | Hamamelidaceae | Dahlia |   |   | Virtuose
Dahlia Thunb.  'Thaler' |   | Hamamelidaceae | Dahlia |   |   | Thaler
Dahlia Thunb.  'C'Nova pourpre' |   | Hamamelidaceae | Dahlia |   |   | C'Nova pourpre



</body>

</html>

**Comment by SiropOps** [comment]
Merci ajouter la colonne ID, pour éviter tout problème

**Comment by Paris75012** [comment]
c'est bien noté.
merci

**Comment by Paris75012** [comment]
[Export_SC_Dahlia_Thunb_06-11-2023_12_38_30.xlsx](https://github.com/Computaceae-IT/cit-ticketing/files/13266001/Export_SC_Dahlia_Thunb_06-11-2023_12_38_30.xlsx)

**Comment by Paris75012** [comment]
Les 2 fichiers : BOTA-NOM & BOTA-SC relatifs à Dahlia Thunb.
