### ISSUE TITLE
[CULT] recherche par numéro après changement de nom

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1361]
Url : https://g.botalista.community/#/cultivated/list/?filters=%7B%22node%22:%7B%22typeEntite%22:%22B%22,%22nodes%22:%5B%7B%22typeEntite%22:%22C%22,%22key%22:%22alive%22,%22operator%22:%22equals%22,%22values%22:%5Btrue%5D,%22editing%22:false,%22_flash%22:true%7D%5D,%22logicalOperators%22:%5B%5D%7D,%22editing%22:false,%22saved%22:false,%22name%22:%22%22%7D
Username : buchschacher

Description : idem ici en recherchant par numéro c'est l'ancien nom du spécimen qui apparait et pas le nouveau nom accepté!

**Comment by SiropOps** [comment]
https://g.botalista.community/#/cultivated/list/?q=Ceterach%20officinarum&filters=%7B%22node%22:%7B%22typeEntite%22:%22B%22,%22nodes%22:%5B%7B%22typeEntite%22:%22C%22,%22key%22:%22alive%22,%22operator%22:%22equals%22,%22values%22:%5Btrue%5D,%22editing%22:false,%22_flash%22:true%7D%5D,%22logicalOperators%22:%5B%5D%7D,%22editing%22:false,%22saved%22:false,%22name%22:%22%22%7D

**Comment by SiropOps** [comment]
https://g.botalista.community/#/cultivated/list/?q=Asplenium%20ceterach&filters=%7B%22node%22:%7B%22typeEntite%22:%22B%22,%22nodes%22:%5B%7B%22typeEntite%22:%22C%22,%22key%22:%22alive%22,%22operator%22:%22equals%22,%22values%22:%5Btrue%5D,%22editing%22:false,%22_flash%22:true%7D%5D,%22logicalOperators%22:%5B%5D%7D,%22editing%22:false,%22saved%22:false,%22name%22:%22%22%7D

**Comment by SiropOps** [comment]
Moi, ça fonctionne bien ?! Attention, des modifications peuvent prendre un certain temps, voir même pendant la nuit (normalement c'est une exception)
