### ISSUE TITLE
[S.L] Bota-SC : anomalie exportation Excel

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1362]
Url : https://jbp.botalista.community/#/
Username : paris

Description : Bonsoir Cyril, 

Nathalie, l'une de nos utilisatrices de Botalista,  m'a fait remonté une anomalie au niveau de la date de l'export Excel. 

Elle m'a fait part  egalement d'autres  anomalies (réparation fichier Excel). 

Je te fournirai les captures d'écran via Githhub.

Bien à toi, 

Vincent Lipa

**Comment by SiropOps** [comment]
Il manque des informations.

Bien à toi, Cyril
