### ISSUE TITLE
[CULT] BOTA-SC : non correspondance de la détermination accepté apès modification de la détermination accepté du SA 20163025G

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1371]
Url : https://jbp.botalista.community/#/cultivated/view/58191
Username : paris

Description : Bonjour Cyril,
Je rencontre cette anomalie.
Bien à toi, 
Vincent Lipa

**Comment by Paris75012** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/74540524/a52377ca-38c6-4954-bf7e-2a4412f4a473)
