### ISSUE TITLE
[NOM] bug synonymie

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1377]
Url : https://g.botalista.community/#/nomenclature/view/114233?tab=2
Username : buchschacher

Description : Comment est-ce possible de consulter la synonymie d'un nom et que le nom principale n'est pas le même que l'espèce consultée ? Ici chez Aster bellidiastrum (L.) Scop. devient Doronicum bellidiatrum L. quand on consulte la Synonymie?

**Comment by SiropOps** [comment]
Il faut aller https://g.botalista.community/#/nomenclature/view/114233?tab=3

Là, le nom n'est pas accepté ou modifié pour le projet JAR (le votre). Du coup, tu as les synonymie de la WFO
