### ISSUE TITLE
[ACQ] Impossible de lier un spécimen cultivé depuis acquisition

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1383]
Url : https://ncy.botalista.community/#/acquisition/view/31699
Username : beghoura

Description : Salut Cyril,

Il est aujourd'hui impossible de lier un spécimen cultivé depuis le volet acquisition

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/13a152ed-ac1a-4f28-8438-5292dc48efa3
