### ISSUE TITLE
[ACQ] H en J

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1384]
Url : https://ncy.botalista.community/#/acquisition/view/31699
Username : beghoura

Description : Re,

Avant quand nous créions une acquisition en horticole, le numéro BL devenait xxxxxxxxH
Désormais c'est un J qui vient terminer ce numéro. Est ce normal?

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/c9c063aa-8605-40d8-8b10-2c486d2d5649
