### ISSUE TITLE
[ACQ] pays

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1387]
Url : https://g.botalista.community/#/acquisition/view/69807
Username : buchschacher

Description : Le pays reste sur ammérique alors que France a été sélectionné même quand on recommence l'opération!!!!

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/dcf17347-5f4f-4b5f-a745-48f2570e989b
