### ISSUE TITLE
[CULT] BOTA-SC : rubrique "Propagation" grisée du SC n° 202111813N0 (Alchemilla alpina)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1389]
Url : https://jbp.botalista.community/#/cultivated/view/60259
Username : paris

Description : Bonjour Cyril, 
Mon collègue (Nicolas du Parc Floral) m'a fait remonter cette anomalie. 
Bien à toi, 
Vincent Lipa

**Comment by Paris75012** [comment]
![Capture botalista](https://github.com/Computaceae-IT/cit-ticketing/assets/74540524/d7921593-14a6-43d1-a36f-9f273ed6ffbe)

**Comment by SiropOps** [comment]
Ce n'est pas une anomalie, c'est prévu; lors qu'un spécimen cultivé est planté (Mise en collection), on ne peut plus faire de repiquage... Évolution à soumettre à le CT?

**Comment by Paris75012** [comment]
Cyril,
Effectivement, Evolution à soumettre à la CT

Bien  à toi,

Vincent Lipa

De : Cyril Boillat ***@***.***>
Envoyé : mardi 19 décembre 2023 15:44
À : Computaceae-IT/cit-ticketing ***@***.***>
Cc : Lipa, Vincent ***@***.***>; Comment ***@***.***>
Objet : Re: [Computaceae-IT/cit-ticketing] [CULT] BOTA-SC : rubrique "Propagation" grisée du SC n° 202111813N0 (Alchemilla alpina) (Issue #1389)

* Ce message a ete emis par un expediteur externe *
Prenez garde aux liens et aux pieces jointes. Ne fournissez jamais votre mot de passe de connexion Ville de Paris.

________________________________

Ce n'est pas une anomalie, c'est prévu; lors qu'un spécimen cultivé est planté (Mise en collection), on ne peut plus faire de repiquage... Évolution à soumettre à le CT?
