### ISSUE TITLE
[IND] problème code IS !!

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1397]
Url : https://neu.botalista.community/v2/fr/indexseminum/list
Username : maire

Description : Salut,
Je veux générer les codes IS, j'ai fait un tri personnalisé (ou j'ai aussi essayé avec un tri multiple sur BLS), je veux mettre les récoltes natures en premier. Mais quand je demande de générer les numéros, les récoltes Jardin sortent en premier dans le numéro. Ca veut dire que mon tri n'est pas respecté.
Help !

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/447673d0-590b-45df-a930-4ce3d01224d4
