### ISSUE TITLE
[CULT] champs nom français manquant

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1404]
Url : https://bord.botalista.community/#/cultivated/view/176236
Username : kassen

Description : Lorsque je suis sur un taxon qui est un cultivar le champ nom commun n'apparait pas. exemple 20230565,

merci

**Comment by SiropOps** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/8d9a50bb-645a-476c-8181-5962e83dcc31)

**Comment by SiropOps** [comment]
Bonjour Laura, la bonne année ;-) Un cultivar n'a pas de nom commun, mais un nom commercial.

Bien à toi, Cyril
