### ISSUE TITLE
[IND] Retiré un lot de l'IS

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1408]
Url : https://g.botalista.community/v2/fr/indexseminum/list
Username : buchschacher

Description : Plus possible de retiré un lot dans l'IS?? Cela a fonctionné avec les premiers mais s'est arrêté brutalement de fonctionner! Donc Impossible de travailler sur l'IS avec ce bug ci.

**Comment by SiropOps** [comment]
Hello, désolé mais ça marche chez moi, même sur le 20191481 ?!
