### ISSUE TITLE
[REC] lié la récolte à l'aquisition qu'on est entrain de faire suite à une multiplication

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1412]
Url : https://g.botalista.community/v2/fr/harvest/view/id/13415
Username : buchschacher

Description : Comme d'habitude je viens à créer une récolte suite à la création d'une acquisition (suite à une multiplication pour créer un lot de jardin pour l'IS), sauf qu'un fois la récolte crée, elle n'apparait pas dans l'acquisition que je suis entrain de faire comme c'était le cas dans la version d'avant? Je vois bien qu'on peut aussi créer une acquisition suite à une récolte mais je ne veux pas d'une nouvelle acquisition, j'aimerai rester sur celle où je suis entrain de travailler comment faire?

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/3af513a5-2b7c-46bb-8a0c-9c811b045d17
