### ISSUE TITLE
[REC] Problème de coordonnées

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1414]
Url : https://g.botalista.community/v2/fr/harvest/edit/id/13413
Username : wells

Description : Lorsqu'on rentre des coordonnées GPS pour une récolte, la map nous envoie dans l'espace....
Par contre, quand on rentre la géolocalisation du lieu-dit, ça nous envoie au bon endroit, mais ce n'est pas aussi précis que les coordonnées. J'ai essayé de retourner les coordonnées dans tout les sens, mais ça ne marche pas. Il y a eu une mise à jour, et c'est depuis ce jour là que ça ne fonctionne plus pour moi.

**Comment by SiropOps** [comment]
Hello,

https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/c8fbbafa-37b6-41f3-8e79-5a122ff3215f
