### ISSUE TITLE
[IND] Impossible de retire un lot de l'index ou de supprimer un lot du module "lot de semences"

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1430]
Url : https://ncy.botalista.community/v2/fr/indexseminum/list
Username : beghoura

Description : Tout est dit dans le titre.
Message d'erreur : "Erreur, cet objets est liés à un autre modul"
PS : Pas de "s" à lié ;)

**Comment by SiropOps** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/20beeac6-e7f9-4e41-b174-8dbce26d8f84)

**Comment by SiropOps** [comment]
Hello,
normal l'IS est défini. il faut supprimer l'IS courrant pour pouvoir le retirer

**Comment by SiropOps** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/d572a1a1-8342-45ed-8624-daf5ac9c4ee5)
