### ISSUE TITLE
[NOM] Comment supprimer un taxon?

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1433]
Url : https://g.botalista.community/#/nomenclature/edit/459475
Username : baumler

Description : Impossible de supprimer le nom "caraganae Hohen" au rang de division (ce qui est une erreur, il s'agit d'un epithète de nom d'espèce, qui existe d'ailleurs déjà) : https://g.botalista.community/#/nomenclature/view/459475
Le système refuse avec le message "L'entité est utilisée dans les taxons suivants : 33652" bien que dans Taxon il n'y a à priori aucune info enregistrée.
Comment faire?

**Comment by SiropOps** [comment]
Désolé, bug dans les données en base. 
C'est fait, merci
