### ISSUE TITLE
[REC] bug récolte impossible à enregistrer et bug lenteur Botalista

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1435]
Url : https://g.botalista.community/v2/fr/harvest/edit
Username : buchschacher

Description : Bloquée pour travailler sur l'index seminum: créer des lots de jardin à cause qu'il n'est plus possible de créer une récolte. Aucun projet ne s'inscrit alors que c'est obligatoire à la création de la récolte! Nous sommes sur ce gros travail d'enregistrement cette semaine pour l'IS et sommes bloquées (Marylin et moi) depuis ce matin. Egalement la base de donnée qui est trop lente pour travailler (en tout cas sur mon ordinateur pas tester ailleurs, j'ai pourtant fait F5 rien ne change. Merci!

**Comment by SiropOps** [comment]
Hello, je t'ai répondu pour la notion de projet. Pour la lenteur, il semble que le problème vient du réseau Ville de Genève. Je ne constate aucune lenteur sur les serveurs. Désolé
