### ISSUE TITLE
[REC] Impossible de créer un filtre pour une recherche sur les récoltes

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1454]
Url : https://g.botalista.community/v2/fr/harvest/list
Username : palese

Description : Indispensable pour comparer ce qui a été ou n'a pas été migré de la "Bleue".

**Comment by SiropOps** [comment]
Bonjour,
As-tu bien suivi la vidéo de présentation diffusé lors de la dernière mise à jour ?

https://wiki.botalista.community/bin/view/Computaceae-IT/Botalista/Documentation/BOTA-FILTER%20%3A%20Gestion%20des%20filtres%20de%20recherche/

Si oui, merci de préciser quelle opération exacte ne marche pas.
