### ISSUE TITLE
[REC] Enregistrer deux récoltes différentes de la même personne

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1456]
Url : https://ntm.botalista.community/v2/fr/harvest/edit?autoClose=true
Username : abour

Description : Bonjour Cyril,
J'ai tenté d'enregistrer des récoltes de la même personne, le même mois, mais à des endroits différents, et un message d'erreur s'affiche : "Il existe un enregistrement avec les mêmes propriétés"
Comment faire ?
Merci !
Aurélien

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/38598e9c-3c01-42a6-820b-bb8d93de5b3d
