### ISSUE TITLE
[S.L] GPS

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1460]
Url : https://ncy.botalista.community/v2/fr/home
Username : sébastien antoine

Description : Bonjour Cyril,

C'est Sébastien du jardin botanique de Nancy,

Nous réfléchissons à l'achat d'un nouveau GPS pour nos récoltes de semences, 

Tu aurais des suggestions de modèles entièrement compatibles avec Botalista ?

Bonne journée !

Bien cordialement

Sébastien

**Comment by SiropOps** [comment]
Bonjour Sébastien, écoute, je n'ai pas suggestion précise. Tous les appareils dont la précision est suffisante pour vous et qui permettent de sortir une valeur d'imprécision en mètre sont compatible avec l'application.
Je reste à dispo pour échanger; je serai sur Nancy le 15.03 si jamais ;-)

Bien à toi.

Cyril
