### ISSUE TITLE
[REC] Champ "Nombre d'individus observés" à modifier

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1464]
Url : https://g.botalista.community/v2/fr/harvest/edit/id/13147
Username : palese

Description : Actuellement il y a une section qui s'appelle " nombre d'individus observés". Est-ce que c'est possible de remplacer ce titre par " taille de la population" ? Et d'ajouter à cela une liste déroulante avec les choix suivants:
- individus, exemplaires 
- touffes, coussinets
- tiges
- surface (m2)
Maya

**Comment by RPalese** [comment]
Spécifications à préciser. Je ferme donc ce ticket
