### ISSUE TITLE
[REC] !Au secours!

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1475]
Url : https://g.botalista.community/v2/fr/harvest/edit?autoClose=true
Username : buchschacher

Description : Aucun projet ne s'inscrit / obligatoire pour pouvoir enregistrer la récolte!

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/c8345918-d8d3-4cd3-a3ed-3fa5ac67dcf5
