### ISSUE TITLE
[ACQ] Non affichage de la récolte

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1495]
Url : https://collections-vegetales.nantes.fr/#/acquisition/edit/
Username : amuller

Description : Une fois la récolte créée et sauvegardée, elle ne s'affiche pas dans l'onglet. Il faut aller la rechercher. Pour Aurélien ça fonctionne correctement.

**Comment by SiropOps** [comment]
Uploading screen-capture.mp4…
