### ISSUE TITLE
[LOC] Erreur changement Aire et speciment cultivé liée

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1505]
Url : https://briss.botalista.community/#/location/view/176?tab=1
Username : maccagni

Description : Bonjour Cyril, j'ai remarqué un problème avec les zones :
J'avais : Aire1, avec group1. J'ai affecté les espèces cultivées au groupe1. Puis j'ai déplacé le groupe1 vers Aire2. Cependant, les plantes qui sont maintenant dans le groupe1 apparaissent toujours cultivées dans la zone1, tout comme les nouvelles espèces ajoutées au groupe1 appartiennent toujours à la zone1.
Dans le cas précis de mon instance botalist, il s'agit des Aree decorative (Aire2), Lungolago(Aire1) e Mellifere(group1).

**Comment by SiropOps** [comment]
C'est toujours la cas ?! La mise à jour des emplacements ce fait la nuit (bientôt plus cas) et n'est donc pas "instantanée"
