### ISSUE TITLE
[CULT] BOTA-SC : création impossible à partir du 2008934J

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1509]
Url : https://jbp.botalista.community/#/cultivated/edit/
Error message : could not execute statement; SQL [n/a]; constraint [ind_number_unique]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Username : dumas

Description : null

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://jbp.botalista.community/api/cultivated/
Request method: POST
Status Code: 405 (Method Not Allowed)
Data send: 
 {"number":null,"parent":{"id":58769,"uid":"ad777c0c-213f-4d6a-bacf-01fb6b59d6a2","typeEntite":"J"},"goal":{"id":1,"name":"collection"},"sector":{"version":0,"key":"Pôle indigène","value":"Pôle indigène","idFunctionalUnit":7,"uid":"60fcb65e-5ef9-4d82-adbf-f0b1852a78b2","location":{"typeEntite":"Site","version":0,"idLocation":3,"uid":"3a6c2ad1-b247-448d-9b81-d5eb36664dc4","name":"Parc Floral","completeName":"Parc Floral","code":"VPPFP"},"type":"enum_sector","name":"Pôle indigène","archive":false},"responsible":null,"sex":null,"areaRepartition":"Eurasiat.\n","plate":{"responsible":{"uid":"d935d725-215c-41c0-ba59-f931ee8c9269","forename":"Aurélia","surname":"Dumas","initial":"A.D.","_lang":"fr"},"date":"2024-04-03","datePrecision":"day","simplePlateState":"enum_good","doublePlateState":"enum_missing"},"note":null,"oldLocations":[]}
 Error Type: com.botalista.lib.core.errors.container.CriticalError
Error message: 
 could not execute statement; SQL [n/a]; constraint [ind_number_unique]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by SiropOps** [comment]
L’acquisition a été supprimé. Impossible de reproduire le problème
