### ISSUE TITLE
[ACQ] Droits Jardin d'agronomie Tropicale

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1531]
Url : https://ntm.botalista.community/#/acquisition/view/389
Username : abour

Description : Bonjour Cyril,
Nous avons un problème sur les droits du jardin d'agronomie tropicale. Nous ne pouvons pas créer de spécimen cultivé : droits insuffisants.
Ca me concerne, mais également les 3 collègues qui y travaillent : Jean Christophe Ribes, Magali Rouillard, Galaad Hainglaise.
Merci !

**Comment by SiropOps** [comment]
Problème dans les données; il y avait des Majuscule dans le nom du secteur; j'ai modifié
