### ISSUE TITLE
[CULT] BOTA--SC : complétion non exhaustive des secteurs à partir du filtre élaboré (champ : secteur)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1539]
Url : https://jbp.botalista.community/#/cultivated/list/
Username : paris

Description : Bonjour Cyril, 
La complétion des secteurs du JBP n'apparait pas de manière exhaustive depuis le secteur du filtre élaborée. 

Cordialement, 

Vincent Lipa

**Comment by SiropOps** [comment]
C'est normal, ce champ n'affiche que les 10 premiers résultats. Pour affiner, il faut taper les lettres.

Bien à toi.
