### ISSUE TITLE
[CULT] BOTA-SC : le lien hypertexte du secteur 'TACOTS' aboutit au secteur 'PAVILLONS'

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1540]
Url : https://jbp.botalista.community/#/cultivated/view/2073
Username : paris

Description : Bonjour Cyril, 
Nous rencontrons toujours l'anomalie décrite dans le titre du ticket de support.

Bien à toi, 
Vincent Lipa

**Comment by Paris75012** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/74540524/bfa58ff8-8022-4ec6-9b98-72fe5bb13cf0)

**Comment by Paris75012** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/74540524/0cd79299-2c32-43f8-9e05-2145cfae6ece)

**Comment by Paris75012** [comment]
Le lien hypertexte du secteur 'TACOTS' aboutit au secteur 'PAVILLONS'

**Comment by SiropOps** [comment]
Le secteur TACOTS n'existe plus / pas dans la liste des secteurs ?!
