### ISSUE TITLE
[CULT] Bug Récolte

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1542]
Url : https://ncy.botalista.community/#/cultivated/view/158098
Username : douglas tavares

Description : Bonjour Cyril,

Depuis hier je constate un bug sur la fenêtre qui s'ouvre quand on veut remplir les informations de récolte au moment de création d'une nouvelle acquisition. 

Après avoir remplir toutes les infos et cliquer sur sauvegarder, la fenêtre se ferme mais rien n'est enregistré. J'ai essayé plusieurs fois entre hier et aujourd'hui, en ajoutant des différentes acquisitions et le bug persiste. Je me souviens (et Carl m'a confirmé) que cela été déjà arrivé auparavant. 

Pourriez-vous en vérifier SVP? 
Merci d'avance 

Douglas

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/d2f824ca-2378-4dbf-a29a-bed99eb45816
