### ISSUE TITLE
[ACQ] BOTA-SA : Export Excel sans secteur (1417 SA)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1543]
Url : https://jbp.botalista.community/#/acquisition/view/50457
Username : paris

Description : Bonjour Cyril, 

Tu trouveras via Github le fichier d'exportation Excel comportant 1417 SA du Parc Floral dont les secteurs sont vides.

Bon début de semaine, 

Bien à toi, 

Vincent Lipa

**Comment by Paris75012** [comment]
[acquisitionExport_24-04-2024_15_18_50.xlsx](https://github.com/Computaceae-IT/cit-ticketing/files/15145851/acquisitionExport_24-04-2024_15_18_50.xlsx)

**Comment by Paris75012** [comment]
Ces acquisitions sont rattachées avec le secteur Tacots du Parc Floral. En lien avec le ticket 1540  (BOTA-SC : le lien hypertexte du secteur 'TACOTS' aboutit au secteur 'PAVILLONS' )
