### ISSUE TITLE
[ACQ] Mise en collection

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1544]
Url : https://gre.botalista.community/#/acquisition/view/8
Username : poletti

Description : Je ne peux pas rattacher le spécimen crée dans la rubrique <acquisition> avec son emplacement correct. Ex: Alpinia zerumber - Serre Subtropicale; Zone terrestre. Et lorsque j'essaie de modifier une spécimen, j'obtiens un message d'erreur ("permission insuffisante") lors de l'enregistrement.

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/7390b1a5-2cc3-4019-84e3-fa6deef4a290
