### ISSUE TITLE
[ACQ] Ajout d'un champ cultivar pour une nouvelle acquisition

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1550]
Url : https://metz.botalista.community/#/acquisition/edit/
Username : egerard

Description : Dernier ticket !
J'ai oublié de t'en parler hier mais j'ai vu que dans les résultats de recherche existait une colonne cultivar, or je n'ai trouvé aucun champ pour l'indiquer dans une nouvelle acquisition !
Ce n'est pas rédhibitoire, en attendant j'ai indiqué le cultivar dans la case "Complément" de la zone dédiée à la nomenclature.
Merci bien !

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/51c9b5d3-d04c-47fd-adb8-604abdaa68da
