### ISSUE TITLE
[NOM] Impossible d'utiliser le champ ID WFO dans un filtre (BOTA-NOM)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1553]
Url : https://g.botalista.community/#/nomenclature/list/
Error message : could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
Username : baumler

Description : Plantage quand on clique sur Appliquer.

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://g.botalista.community/api/nomenclature/filter/value/%25/page/1
Request method: PUT
Status Code: 405 ()
Data send: 
 "{\"node\":{\"typeEntite\":\"B\",\"nodes\":[{\"typeEntite\":\"C\",\"key\":\"wfoId\",\"operator\":\"equals\",\"values\":[\"wfo-0000019940\"],\"editing\":false,\"_flash\":true}],\"logicalOperators\":[]},\"editing\":false,\"saved\":false,\"name\":\"\"}"
 Error Type: com.botalista.lib.core.errors.container.CriticalError
Error message: 
 could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet

**Comment by cjbeat** [comment]
![Uploading ErreurFiltreWFO.JPG…]()
