### ISSUE TITLE
[NOM] Deux instances du champ Citation d'auteurs dans le filtre (BOTA-NOM)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1555]
Url : https://g.botalista.community/#/nomenclature/list/
Username : baumler

Description : Il existe deux instances du champ Citation d'auteurs dans le filtre de BOTA-NOM. La première fonctionne correctement, la seconde provoque l'erreur "Type de clé non supportée" / "entityextnewfront" et est en principe sans utilité.

**Comment by cjbeat** [comment]
![FiltreBotaNom](https://github.com/Computaceae-IT/cit-ticketing/assets/26811087/66a20bd3-fde4-4100-b9ad-68e438acbe1e)
