### ISSUE TITLE
[CULT] Nom de genre n'apparait pas sur l'étiquette

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1578]
Url : https://bord.botalista.community/#/cultivated/view/173613
Username : kassen

Description : le nom de genre n'apparait pas sur l'extracation de l'étiquette pour l'accession 20110019io 

merci

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/18626c55-2436-496b-b3c8-9de32523c819
