### ISSUE TITLE
[CULT] BOTA-SC : Bug : SC issu d'un SA dupliqué de G vers J

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1581]
Url : https://jbp.botalista.community/#/cultivated/list/?filters=%7B%22node%22:%7B%22typeEntite%22:%22B%22,%22nodes%22:%5B%7B%22typeEntite%22:%22C%22,%22key%22:%22alive%22,%22operator%22:%22equals%22,%22values%22:%5Btrue%5D,%22editing%22:false,%22_flash%22:true%7D%5D,%22logicalOperators%22:%5B%5D%7D,%22editing%22:false,%22saved%22:false,%22name%22:%22%22%7D
Username : paris

Description : Bonjour Cyril, 

Je rencontre, depuis  notre instance, un plantage lorsque je souhaite lier à un spécimen cultivé à un SA dupliqué en J à partir de G. Je constate que ce processus fonctionne parfaitement à partir du Bac à sable. J’avais rencontré la même anomalie il y a quelques semaines.

Bien à toi, 

Vincent Lipa

**Comment by Paris75012** [comment]
20208934J > BUG
20195147G -> BUG

20172201 G  Il n’est pas possible d’ajouter une nouvelle acquisition cette année (+1000) 
20182328G -> Il n’est pas possible d’ajouter une nouvelle acquisition cette année (+1000) 
20195147G -> BUG
