### ISSUE TITLE
[CULT] BOTA-SC : Il n’est pas possible de créer une nouvelle acquisition (plus de 10 000 acquisitions, cette année)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1582]
Url : https://jbp.botalista.community/#/cultivated/list/
Username : paris

Description : Bonjour Cyril, 

Je rencontre toujours cette même anomalie pour les années 2017 et 2018  :BOTALISTA m’indique qu’il n’est pas possible de créer une nouvelle acquisition (plus de 10 000 acquisitions, cette année). selon toi, l'anomalie n'est pas corrigeable malheureusement.

Bien à toi, 
Vincent Lipa

**Comment by SiropOps** [comment]
Non, désolé, on ne peut pas dépasser 9'999 acquisition par année. Mais je travail sur une amélioration, avec l'introduction de lettre dans la numéro d’acquisition. Certainement pour cette fin d'année. Bien à toi, Cyril
