### ISSUE TITLE
[CULT] Erreur générale !!

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1588]
Url : https://jbp.botalista.community/#/cultivated/list/?filters=%7B%22type%22:%22selector%22,%22key%22:%22number%22%7D
Username : paris

Description : Bonjour Cyril, 

je n'ai pus d'accès à BOTA-SC!!

Bien à toi, 

VIncent Lipa

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://jbp.botalista.community/api/cultivated/filter/meta/
Request method: GET
Status Code: 503 ()
Data send: 
 undefined
 Error Type: undefined
Error message: 
 undefined

**Comment by Paris75012** [comment]
c'est revenu !
