### ISSUE TITLE
[NOM] manque Famille ???

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1590]
Url : https://g.botalista.community/#/nomenclature/view/300162
Username : buchschacher

Description : Ce nom encore largement utilisé en CH, il lui manque la famille on passe directement de l'espèce au règne ??? du coup le nom de la famille ne sort pas sur l'étiquette....

**Comment by SiropOps** [comment]
Hello Céline, tu trouveras une vidéo pour résoudre ton "problème" de Famille. Je reste à dispo.

https://github.com/Computaceae-IT/cit-ticketing/issues/1578
