### ISSUE TITLE
[CULT] cultivar nom vernaculaire

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1592]
Url : https://bord.botalista.community/#/cultivated/view/176496
Username : kassen

Description : A chaque fois qu'il y a un cultivar, il n'y a plus le champs non vernaculaire,

merci

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/1a4d44e1-6a23-460f-87d6-025cf4eb3527
