### ISSUE TITLE
[S.L]  impossible saisie d'une acquisition

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1593]
Url : https://mey.botalista.community/v2/fr/home
Username : callendret

Description : Bonjour Cyril,
Je souhaite saisir une nouvelle acquisition : graines de Silene swertiifolia Boiss. reçues du Mnhn Paris. Sur la WFO figure : Silene chlorifolia subsp. swertiifolia (Boiss.) Ghaz.(unchecked)...mais je n'arrive pas à valider cette acquisition, même en cochant "temporaire". Comment faire ?
Merci d'avance et très belle semaine,

**Comment by SiropOps** [comment]
https://github.com/Computaceae-IT/cit-ticketing/assets/35902374/81e20f4e-7ab8-405b-82e5-c99f1c8f7432
