### ISSUE TITLE
[WOR] BOTA-REC : Coordonnées CH1903+ 

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1603]
Url : https://jbp.botalista.community/v2/fr/workflow/edit/mode/hart2is/step/BOTA_HART
Username : paris

Description : Bonjour Cyril, 
Les coordonnées CH1903+ ne sont pas reconnues par le système. 
Exemple de coordonnées (E/N) : 234340, 419757

Bien à toi, 
Vincent Lipa

**Comment by Paris75012** [comment]
![image](https://github.com/Computaceae-IT/cit-ticketing/assets/74540524/711d2bb7-b3c8-4e44-b27a-efc433ee2ccb)

**Comment by SiropOps** [comment]
![image](https://github.com/user-attachments/assets/2bc1435a-151d-4712-af08-b9c4cc03b051)

**Comment by Paris75012** [comment]
J'ai pourtant obtenu ces coordonnées à partir de l'application mobile FLORA HELVETICA  :(
