### ISSUE TITLE
[AUT] Modification d'une autorité

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1611]
Url : https://g.botalista.community/v2/fr/authority/edit/id/41453
Username : sibadmin

Description : Quand je tente de modifier l'autorité (C.Presl) Grosser en (C.Presl) Gross le sytème me signale que cela aura un impact sur des acquisitions dont le nom n'a rien à voir avec cette autorité (voir capture d'écran)
Raoul

**Comment by RPalese** [comment]
![Modif_autorite](https://github.com/user-attachments/assets/55250ff5-8b3d-4995-89e1-215d18912ddb)

**Comment by SiropOps** [comment]
Bonjour, Dans ce cas précis, le système indique que c'est le taxon qui va être modifié. En effet, il y a une relation de synonymie entres les noms avec l'autorité (C.Presl) Grosser (voir ci-dessous).
De manière général, il n'est pas possible de modifier une autorité importée par la WFO, car cela modifierait le nom WFO, qui est immuable. Si on souhaite vraiment avoir cette différence, il faut créer un doublon.
