### ISSUE TITLE
[CULT] permission suppression spécimens cultivés

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1612]
Url : https://neu.botalista.community/#/cultivated/edit/55150&state=c5ee36a9-0ace-46d7-9cd5-d15a024e9508&session_state=fc27ff85-9ebd-4e04-8144-f3f08ec7d64e&code=53c4590a-4470-4f71-a494-5b072a7e23eb.fc27ff85-9ebd-4e04-8144-f3f08ec7d64e.1f056c26-6f12-4be8-9029-1dee0ab9ca61
Username : maire

Description : Bonjour,
Je ne peux pas supprimer de spécimens cultivés (permission insiffisante), pourtant je suis admin de notre instance.
Comment faire ? la supression de SC est-elle veroulliée ?
Merci,

**Comment by SiropOps** [comment]
Oui. Il n'est pas possible de supprimer un SC une fois qu'il a été planté; choix de la commission technique d'il y a bien longtemps. Mais dans la prochaine mise à jour, tu pourras, seulement les ADMIN. En attendant, tu veux que je le supprime ?
