### ISSUE TITLE
[NOM] Problème migration

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1615]
Url : https://ncy.botalista.community/#/nomenclature/view/460033
Username : berthold

Description : Bonjour Cyril,

Je viens de trouver un bug de migration.
Tous les cultivars de Fuchsia ont était rattaché à Fuchsia ? et non pas Fuchsia L.
Il en a beaucoup donc serait t'il possible de les changer en Fuchsia L. en mode "batch"?

Merci d'avance
Carl

**Comment by SiropOps** [comment]
J'ai fais le BATCH à la main ;-)
