### ISSUE TITLE
[CLV] Suppression de collectif de personnes

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1617]
Url : https://ntm.botalista.community/v2/fr/collective/edit/id/218260
Username : abour

Description : Hello,
Est-il possible de supprimer ce collectif qui n'est raccroché à aucune récolte ?
Bour, AB & Besson

Il reste un doublon de nom de personne :
aurélien Bour

à raccrocher à :
Aurélien Bour

Merci ;)

**Comment by SiropOps** [comment]
Ce'st fait ;-)
