### ISSUE TITLE
[NOM] Impossible d'attacher un synonyme

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1622]
Url : https://ncy.botalista.community/#/nomenclature/view/1605595?tab=2
Username : berthold

Description : Salut Cyril,

Je suis en train d'enregistrer Utricularia dichotoma var. novae-zelandiae (Hook.f.) R.W.Jobson et je vois que notre base WFO n'est pas à jour concernant ce taxon car il existait encore Utricularia novae-zelandiae (l'ancienne vue taxonomique) en tant que accepté. U.dichotoma subsp. novae-zelandiae n'existait pas encore donc je l'ai crée. Le soucis c'est que la base ne me laisse pas ajouter U. novae-zelandiae en tant que synonyme - je pense que c'est du au fait que il a déjà des synonymes attachés mais si c'est bien ça c'est dommage car la chaine de synonymie devrait suivre le "parent". Si tu peux confirmer le source du soucis et comment le régler ça serait top merci =)
Bonne journée,
Carl

**Comment by SiropOps** [comment]
Réglé par Whatapp ;-)
