### ISSUE TITLE
[NOM] BOTA-NOM : Dryopteris affinis 'Pinderi'

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1623]
Url : https://jbp.botalista.community/#/nomenclature/list/?q=%25&filters=%7B%22node%22:%7B%22typeEntite%22:%22B%22,%22nodes%22:%5B%7B%22typeEntite%22:%22B%22,%22nodes%22:%5B%7B%22typeEntite%22:%22C%22,%22key%22:%22nodeType%22,%22operator%22:%22equals%22,%22values%22:%5B%22%7B%5C%22version%5C%22:0,%5C%22id%5C%22:600,%5C%22key%5C%22:%5C%22600%5C%22,%5C%22value%5C%22:%5C%22genus%5C%22%7D%22%5D,%22editing%22:false,%22_flash%22:true%7D%5D,%22logicalOperators%22:%5B%5D%7D,%7B%22typeEntite%22:%22B%22,%22nodes%22:%5B%7B%22typeEntite%22:%22C%22,%22key%22:%22nameNode%22,%22operator%22:%22contains%22,%22values%22:%5B%22dryopteris%22%5D,%22editing%22:false,%22_flash%22:true%7D%5D,%22logicalOperators%22:%5B%5D%7D%5D,%22logicalOperators%22:%5B%22and%22%5D%7D,%22editing%22:false,%22saved%22:false,%22name%22:%22%22%7D
Username : paris

Description : Bonjour Cyril, 

Le rang (Famille- Dryopteridaceae) n'est pas affiché dans le hiérarchie taxonomique de ce taxon (Dryopteris affinis 'PinderI'). La requête à partir de la famille  de ce taxon n'apparait pas dans les résultats depuis BOTA-SC.

Bien à toi, 
Vincent Lipa

**Comment by Paris75012** [comment]
![image](https://github.com/user-attachments/assets/36d290ca-b39e-424f-859d-4039d9292ec7)

**Comment by Paris75012** [comment]
![image](https://github.com/user-attachments/assets/b895a339-60f3-490b-9665-f582bd5ef415)

**Comment by Paris75012** [comment]
![image](https://github.com/user-attachments/assets/1748a1c2-ee71-4b93-939a-c94b93e45d33)

**Comment by Paris75012** [comment]
![image](https://github.com/user-attachments/assets/797b0760-4111-42af-bdf7-870c41ecdd42)

**Comment by Paris75012** [comment]
![image](https://github.com/user-attachments/assets/b7d58eaa-9f09-433a-95a8-f2a585ab18f0)

**Comment by Paris75012** [comment]
![image](https://github.com/user-attachments/assets/dae1e2d9-9780-437c-8224-7fb5fbb58e26)
