### ISSUE TITLE
[COL] Erreur affichage données (collections)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1627]
Url : https://g.botalista.community/#/collection/list/?q=.&page=1&orderBy=name&reverse=0
Username : baumler

Description : Dans la liste des collections thématiques, les colonnes "Responsable(s)" et "Référent scientifique" affichent le texte "(error, metas = null)" pour l'ensemble des lignes.

**Comment by cjbeat** [comment]
![collections](https://github.com/user-attachments/assets/97ae50ee-e5d9-4296-af6d-4e9a15dca396)

**Comment by cjbeat** [comment]
![collections2](https://github.com/user-attachments/assets/34b7a231-b1fc-499b-8701-da99d184f14c)

**Comment by cjbeat** [comment]
@SiropOps Le message d'erreur est différent maintenant. J'aurais dit que les 2 colonnes devraient être entièrement remplies par des valeurs (demander au jardinier chef le cas échéant).

**Comment by SiropOps** [comment]
@cjbeat Il y avait en plus un problème dans la migration des données de personnes. Tout est maintenant corrigé.
