### ISSUE TITLE
[S.L] Probléme impression étiquettes

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1628]
Url : https://bord.botalista.community/v2/fr/home
Username : vivent

Description : Bonjour,

Pour imprimer des étiquettes, la première série d'aujourd'hui tout s'est bien passé mais impossible d'avoir l'arbre maintenant pour en faire plus même après plusieurs essais.
Tout en sachant que je le fais avec le compte de Dominique Vivent car même après plus de six mois vous ne m'avez toujours pas donné l'autorisation.

https://drive.google.com/file/d/170rF-Jl3l128PV3zDLWoGHw8riWDLqAl/view?usp=sharing

Cordialement,
Samy Taylor.

**Comment by SiropOps** [comment]
Bonjour Samy, il y a une erreur dans l'utilisation du filtre; il ne faut pas prendre le champ code interne mais le champ Numéro de spécimen cultivé. Voir la capture ci-dessous. 
Concernant l'autorisation, une réponse vous avait été notifiée le 06.10.2023 par mail. Je me suis permis de vous la renvoyer.

Bien à vous.

**Comment by SiropOps** [comment]
![image](https://github.com/user-attachments/assets/d10636e9-c1ab-4ce6-8502-fc395e1fa16f)
