### ISSUE TITLE
[ACQ] Jardin d'agronomie tropicale

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1638]
Url : https://ntm.botalista.community/#/acquisition/view/23030
Username : abour

Description : Bonjour Cyril,

Je n'ai pas accès au secteur "Jardin d'Agronomie Tropicale". On avait pourtant bien créé ce secteur non ?

Merci

**Comment by SiropOps** [comment]
C'est un bug dans la base de donnée avec un Jardin d’Agronomie Tropicale et Jardin d’agronomie tropicale (minuscule) ;-)

Bien à toi
