### ISSUE TITLE
[CULT] cultivated_error_inconsistent_respon

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1641]
Url : https://fribg.botalista.community/#/cultivated/edit/
Username : moser

Description : Salut Cyril,

J'ai ce message d'erreur lorsque je veux créer un SC. As-tu une explication? merci
a plus
Alain

**Comment by SiropOps** [comment]
Bonjour,

c'est lié à la personne que tu as sélectionné. Peut-tu me donner le nom de la personne ?!

J'ai mis à jour le message d'erreur ;-)

Bien à toi
