### ISSUE TITLE
[REC] Impossible de créer une récolte avec des données GPS CH1903+

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1645]
Url : https://g.botalista.community/v2/fr/harvest/edit?autoClose=true&uid=923728882411432210199768475
Username : buchschacher

Description : Ne reconnait pas les point GPS pris en Suisse, je vais devoir bientot créer beaucoup de récolte suite aux courses graines, comment faire?

**Comment by SiropOps** [comment]
https://github.com/user-attachments/assets/9ad78326-4a68-43e8-8ba6-3e50410793d9
