### ISSUE TITLE
[REC] coordonnées

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1649]
Url : https://g.botalista.community/v2/fr/harvest/edit
Username : wells

Description : Les coordonnées sous de format : 4'855'70 / 1'101'61
ne marchent plus.........

**Comment by SiropOps** [comment]
Désolé, mais ce format ne fonctionne pas non plus dans SwissTopo

2'595'000.00, 1'179'338.89
ou
595'000.05, 179'338.87

Le dernier ' ne devrait-il pas être un . !?
