### ISSUE TITLE
[S.L] Matthieu Grillet

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1650]
Url : https://g.botalista.community/v2/fr/home
Username : grillet

Description : Les qrcode n'ont pas le même format et sont illisible

**Comment by SiropOps** [comment]
En effet, les QR code ont changé mais son lisible par l'application. Je regarde avec tes deux collègues de l'informatique si on peut pas organiser une séance / explication ?!

Bien à toi,

Cyril
