### ISSUE TITLE
[LOC] Création archive

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1657]
Url : https://ncy.botalista.community/#/location/view/3?tab=1
Error message : could not execute statement; SQL [n/a]; constraint [ind_loc_vm_tree_explore_id]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Username : beghoura

Description : null

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://ncy.botalista.community/api/location/
Request method: POST
Status Code: 405 ()
Data send: 
 {"typeEntite":"Site","code":"ARC","name":"Archive","description":"Archive des anciens emplacements avec spécimens disparus liés. \nRéalisation des inventaires > à 2023","parent":{"id":3,"typeEntite":"Site"},"locationGeometry":null}
 Error Type: com.botalista.lib.core.errors.container.CriticalError
Error message: 
 could not execute statement; SQL [n/a]; constraint [ind_loc_vm_tree_explore_id]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by SiropOps** [comment]
C'était dans les données, le site Archive avait un parent ;-)
