### ISSUE TITLE
[S.L] BOTA-NOM : droits (secteur Chemin de l'évolution)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1700]
Url : https://jbp.botalista.community/v2/fr/home
Username : paris

Description : Bonjour Cyril, 
Je rencontre également une anomalie liée à la gestion des droits du secteur ‘Chemin de l’évolution’ et l'ajout d'un synonyme à Chenopodiastrum murale.
Bien à toi,
Vincent Lipa

**Comment by Paris75012** [comment]
![image](https://github.com/user-attachments/assets/2d6dcf13-8a3e-48ac-9538-12a0afea271e)

**Comment by Paris75012** [comment]
![image](https://github.com/user-attachments/assets/49324e3c-5dbd-4f7b-8f0e-090c336c575a)

**Comment by SiropOps** [comment]
Tout bon ;-)

**Comment by Paris75012** [comment]
☺

Cordialement

Vincent Lipa
Responsable de la graineterie du Jardin botanique de Paris


***@***.***

Jardin botanique de Paris – Paris.fr<https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiYgMnC0qXaAhXIkywKHcbyAL4QFgguMAA&url=https%3A%2F%2Fwww.paris.fr%2Fjardinbotaniquedeparis&usg=AOvVaw108ymee_CTrfV65b7K05nw>

Bureau :

Ville de Paris
Direction des Espaces Verts et de l'Environnement
Service des Techniques du Végétal et de l’Agriculture
103 avenue de  France
75013 Paris

Graineterie du Jardin botanique de Paris :
Pavillon 5 - Parc Floral  75012 Paris
Tél. : + 33 (0)1 49 57 94 47

De : Cyril Boillat ***@***.***>
Envoyé : mardi 29 octobre 2024 12:08
À : Computaceae-IT/cit-ticketing ***@***.***>
Cc : Lipa, Vincent ***@***.***>; Comment ***@***.***>
Objet : Re: [Computaceae-IT/cit-ticketing] [S.L] BOTA-NOM : droits (secteur Chemin de l'évolution) (Issue #1700)

* Ce message a ete emis par un expediteur externe *
Prenez garde aux liens et aux pieces jointes. Ne fournissez jamais votre mot de passe de connexion Ville de Paris.

________________________________

Tout bon ;-)
