### ISSUE TITLE
[ACQ] Acquisition provisoire en collection vivante

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1705]
Url : https://g.botalista.community/#/acquisition/edit/73157
Username : buchschacher

Description : Je ne peux plus passer une acquisition provisoire en acquisition de collection vivante ?
Il me semble qu'on pouvait éditer à tout moment et changer l'acquisition provioire puisque c'est son but d'être provisoire ?
Dois-je dupliquer l'acquisition pour l'avoir en collection vivante ? Cela me semble vraiment bizzare il me semble avoir pu faire cela plus facilement par le passé?

**Comment by SiropOps** [comment]
Oui, c'est un bug, je viens de le corriger, t'inquiète ;-)
