### ISSUE TITLE
[ORD] BOTA-COMMANDES :

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#1727]
Url : https://jbp.botalista.community/#/order/catalog/edit/
Username : paris

Description : Bonjour Cyril, 

le système m'indique une erreur de fichier après la tentative de télécharger un catalogue de semences. Je te joindrai la capture d'écran à mon ticket de support.

Bien à toi, 

Vincent Lipa

**Comment by Paris75012** [comment]
![image](https://github.com/user-attachments/assets/0a8f1553-0365-4b57-be54-d9f774de5e41)
