### ISSUE TITLE
[CULT] Détail des propagations

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#436]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Thursday Apr 04, 2019 at 08:04 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/1838_

----

Url : https://rc.botalista-dev.ch/#/cultivated/view/51691
Username : sibadmin

Description : Les propagations successives (y compris la première) devraient être montrées sous forme de tableau et chaque ligne devrait être cliquable pour voir l'ensemble des informations d'une propagation sous forme de modale - RP -

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Monday Jul 06, 2020 at 14:33 GMT_

----

#2033

**Comment by RPalese** [comment]
#232
