### ISSUE TITLE
[CULT] Phase de propagation éditables

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#437]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Thursday Apr 04, 2019 at 08:05 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/1839_

----

Url : https://rc.botalista-dev.ch/#/cultivated/view/51691
Username : sibadmin

Description : Les phases de propagation devraient être éditables pour pouvoir mettre à jour le champ "Résultat" a posteriori - RP -

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Monday Jul 06, 2020 at 14:32 GMT_

----

#2033

**Comment by RPalese** [comment]
#232
