### ISSUE TITLE
[CULT] Modification de la date de propagation

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#487]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Wednesday Aug 07, 2019 at 12:24 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/1999_

----

Url : https://g.botalista.community/#/cultivated/view/51938
Username : staehli

Description : On ne peut pas modifier la date de semis. Impossible de changer la date si on s'est trompé !

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Monday Jul 06, 2020 at 14:31 GMT_

----

#2033

**Comment by RPalese** [comment]
#232
