### ISSUE TITLE
[CULT] Modifications Propagation

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#493]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Monday Sep 02, 2019 at 11:48 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/2014_

----

Url : https://g.botalista.community/#/cultivated/view/54162
Username : staehli

Description : Dans Propagation, on ne peut pas y retourner pour faire une modification : erreur de date ou oubli de contenant, etc... !!

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Monday Jul 06, 2020 at 14:31 GMT_

----

#2033

**Comment by RPalese** [comment]
#232
