### ISSUE TITLE
[CULT] Affichage des propagations

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#545]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Thursday Dec 12, 2019 at 09:47 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/2128_

----

Url : https://rc.botalista-dev.ch/#/cultivated/view/54864
Username : sibadmin

Description : Il faut revoir l'affichage des propagations successives, notamment parceque seule la première permet d'accéder au détail de l'emplacement - RP -

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Monday Jul 06, 2020 at 14:30 GMT_

----

#2033

**Comment by RPalese** [comment]
#232
