### ISSUE TITLE
[CULT] Recherche via des filtres : Obtenteurs, Date obtention, Pays obtentions et Nom commercial

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#573]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Thursday Feb 20, 2020 at 12:48 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/2186_

----

Url : https://jbp.botalista.community/#/cultivated/list/
Username : paris

Description : Rebonjour, 

Catégorie : BOTALISTA / SPECIMENS CULTIVES / RECHERCHE 

Nous devons pouvoir rechercher pour nos collections horticoles les informations ci-après à partir du filtre élaborée : 

- Obtenteur 
- Pays obtention 
- Date obtention 
- Nom commercial 

Cette fonctionnalité manquante bloquante est capitale.

Cordialement 

Vincent Lipa

**Comment by RPalese** [comment]
#572

**Comment by RPalese** [comment]
Ce n'est pas un réel "duplicate" car on parle ici des filtres de recherche sur CULT alors que le ticket 572 par de filtres de recherche sur NOM - RP -

**Comment by Paris75012** [comment]
Bonjour Cyril, 
merci pour le déploiement rapide de ces champs. même remarque que pour BOTA-NOM. La liste des "Pays obtenteur" est partiellement par ordre alphabétique. Nous trouvons des pays après le Zimbabwe...

Bien à toi 

Vincent Lipa

**Comment by Paris75012** [comment]
Cyril, 
L'ordre des pays est bon!!!
Cordialement
Vincent Lipa
