### ISSUE TITLE
[CULT] BOTA-SA : volet grisé "Propagation" du SC 20196521h0

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#608]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Friday May 15, 2020 at 07:20 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/2299_

----

Url : https://jbp.botalista.community/#/cultivated/view/48915
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Le volet « Propagation  » du SC  vivant 20186804N1 est désactivé ou grisé.  Je n’ai pas constaté cela pour une autre SC 2019621H0.

Est-ce normal ?

Bien cordialement 

Vincent Lipa

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Monday Jul 06, 2020 at 14:29 GMT_

----

#2033

**Comment by RPalese** [comment]
#232

**Comment by Paris75012** [comment]
Bonjour Cyril, 

le volet  "Propagation" de ce SC 20186804N1 est toujours grisé. Cela est valable pour le SC 20186804N0. Tous les 2 SC sont vivants.
Bien à toi 
Vincent Lipa

**Comment by Paris75012** [comment]
![Screenshot_2021-06-03 Botalista Spécimens cultivés Consultation 42773](https://user-images.githubusercontent.com/74540524/120627079-99701d00-c463-11eb-929a-8b32222df76c.png)

**Comment by Paris75012** [comment]
![Screenshot_2021-06-03 Botalista Spécimens cultivés Consultation 42784](https://user-images.githubusercontent.com/74540524/120627275-ca505200-c463-11eb-98e6-c85805b30634.png)

**Comment by SiropOps** [comment]
C'est tout à fait normal; il est en plantation ce spécimen; (Mise en collection en 2016, donc il est impossible de propager un spécimen mis en collection, il faut soit en créer un nouveau (Repiquage / Multiplication) soit le déplacer (onglet emplacement)

**Comment by Paris75012** [comment]
Merci beaucoup pour cette précision !!!!

Bien à toi

Vincent Lipa
ASE aménagement paysager
Responsable de la graineterie du Jardin botanique de Paris


***@***.***CFE17D.4632F520]

Jardin botanique de Paris – Paris.fr<https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiYgMnC0qXaAhXIkywKHcbyAL4QFgguMAA&url=https%3A%2F%2Fwww.paris.fr%2Fjardinbotaniquedeparis&usg=AOvVaw108ymee_CTrfV65b7K05nw>

Bureau :
Ville de Paris
Direction des Espaces Verts et de l'Environnement
Service des Sciences et Techniques du Végétal Agriculture Urbaine
Jardin Botanique
103 avenue de  France
75639 PARIS Cedex 13
Fax : + 33 (0)1 71 28 57 41

Graineterie du Jardin botanique de Paris :
Pavillon 5 - Parc Floral  75012 Paris
Tél. : + 33 (0)1 49 57 94 47

De : Cyril Boillat ***@***.***
Envoyé : jeudi 3 juin 2021 13:00
À : Computaceae-IT/cit-ticketing
Cc : Lipa, Vincent; Comment
Objet : Re: [Computaceae-IT/cit-ticketing] [CULT] BOTA-SA : volet grisé "Propagation" du SC 20196521h0 (#608)

* Ce message a ete emis par un expediteur externe *
Prenez garde aux liens et aux pieces jointes. Ne fournissez jamais votre mot de passe de connexion Ville de Paris.

________________________________

C'est tout à fait normal; il est en plantation ce spécimen; (Mise en collection en 2016, donc il est impossible de propager un spécimen mis en collection, il faut soit en créer un nouveau (Repiquage / Multiplication) soit le déplacer (onglet emplacement)
