### ISSUE TITLE
[CULT] BOTA-ACQ : rubrique Propagation (non modifiable)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#634]
<a href="https://github.com/cibotalista"><img src="https://avatars3.githubusercontent.com/u/20064643?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cibotalista](https://github.com/cibotalista)**
_Monday Jul 06, 2020 at 07:24 GMT_
_Originally opened as https://github.com/CJB-Geneve/com-botalista-backend/issues/2364_

----

Url : https://jbp.botalista.community/#/cultivated/view/48749
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

La rubrique "Propagation" est non modifiable après le premier enregistrement. L'utilisateur ne peut pas modifier ou ajouter des informations liées à la propagation du SC (spécimens cultivés). 

Cordialement 
Vincent Lipa

**Comment by cibotalista** [comment]
<a href="https://github.com/RPalese"><img src="https://avatars1.githubusercontent.com/u/37696294?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RPalese](https://github.com/RPalese)**
_Monday Jul 06, 2020 at 14:29 GMT_

----

#2033

**Comment by RPalese** [comment]
#232
