### ISSUE TITLE
[ACQ] REACTUALISATION DU TICKET_24_09_2020 : BOTA-REC_TICKET_PARIS_DONNEES_HORTICOLES_30_04_2020

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#667]
Url : https://jbp.botalista.community/#/acquisition/list/
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Suite au ticket du 30/04, Ajouts de champs de recherche du volet "Cultivar " : 

GROUPE HORTICOLE
CATEGORIE HORTICOLE
DATE ENREGISTREMENT DE LA DENOMINATION VARIETALE 
PAYS OBTENTION
OBTENTEUR
DATE OBTENTION
NOM COMMERCIAL
DISTINCTIONS

Nota : La spécificité horticole de notre jardin botanique nécessite l’utilisation quasi quotidienne de ses données à différents niveaux (consultation, mise à jour des collections et des étiquetages). Cette remarque a été formulée début septembre par nos collègues du site de Bagatelle lors d'une réunion relative à la mise en route de BOTALISTA.  

Cordialement 

Vincent Lipa

**Comment by RPalese** [comment]
#574
