### ISSUE TITLE
[CULT] REACTUALISATION : TICKET_PARIS_BOTA-CUL_DONNEES_HORTICOLES_30_04_2020

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#668]
Url : https://jbp.botalista.community/#/cultivated/list/
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Suite au ticket du 30/04, Ajouts de champs de recherche du volet "Cultivar " : 

GROUPE HORTICOLE
CATEGORIE HORTICOLE
DATE ENREGISTREMENT DE LA DENOMINATION VARIETALE 
PAYS OBTENTION
OBTENTEUR
DATE OBTENTION
NOM COMMERCIAL
DISTINCTIONS

Nota : La spécificité horticole de notre jardin botanique nécessite l’utilisation quasi quotidienne de ses données à différents niveaux (consultation, mise à jour des collections et des étiquetages). Cette remarque a été formulée début septembre par nos collègues du site de Bagatelle lors d'une réunion relative à la mise en route de BOTALISTA.  

Cordialement 

Vincent Lipa

  Cordialement

**Comment by RPalese** [comment]
#573
