### ISSUE TITLE
[ACQ] BOTA-SA: TICKET_PARIS_SA_INSTITUT_ORIGINE_21_07_2020

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#72]
Url : https://jbp.botalista.community/#/acquisition/edit/
Username : paris

Description : -----------------------------------------------------------------------------------------------------------------------------------------------------------------
De : Raoul.Palese@ville-ge.ch [mailto:Raoul.Palese@ville-ge.ch] 
Envoyé : mardi 21 juillet 2020 15:41
À : Lipa, Vincent
Cc : Cyril.Boillat@ville-ge.ch; Bellivier, Danièle; Nouri, Didier; Rodrigues, Frederic; Crisnaire, Régis
Objet : RE: TR: BOTA-SA: TICKET_PARIS_SA_INSTITUT_ORIGINE_11_05_2020

Bonjour Vincent, 

Est-ce que tu peux ouvrir un ticket à ce sujet stp? 

Merci et bonne fin de journée 

Raoul 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

De :        "Lipa, Vincent" <Vincent.Lipa@paris.fr> 
A :        "'Raoul.Palese@ville-ge.ch'" <Raoul.Palese@ville-ge.ch> 
Cc :        "Cyril.Boillat@ville-ge.ch" <Cyril.Boillat@ville-ge.ch>, "Crisnaire, Régis" <Regis.Crisnaire@paris.fr>, "Rodrigues, Frederic" <frederic.rodrigues@paris.fr>, "Nouri, Didier" <didier.nouri@paris.fr>, "Bellivier, Danièle" <Daniele.Bellivier@paris.fr> 
Date :        17.07.2020 15:33 
Objet :        TR: BOTA-SA: TICKET_PARIS_SA_INSTITUT_ORIGINE_11_05_2020 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Bonjour Raoul, 
  
Comme suite à notre point téléphonique en date du 16/07 après-midi, je te communique le tableau de comparaison  du champ « INSTITUT D’ORIGINE » entre le JICv2 et BOTALISTA. Je reste à ta disposition pour de plus amples informations. 
  
Bon week-end 
  
Bien à toi   
  
Vincent Lipa 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

De : Lipa, Vincent 
Envoyé : vendredi 22 mai 2020 10:45
À : 'Raoul.Palese@ville-ge.ch'; Cyril.Boillat@ville-ge.ch
Cc : Crisnaire, Régis; Barreau, Christine; Nouri, Didier; Rodrigues, Frederic; Bellivier, Danièle
Objet : BOTA-SA: TICKET_PARIS_SA_INSTITUT_ORIGINE_11_05_2020 
Importance : Haute 
  
  
Re-Bonjour Cyril et Raoul, 
  
En lien avec mon ticket de support « BOTA-SA: TICKET_PARIS_SA_INSTITUT_ORIGINE_11_05_2020 », je vous communiquerai le fichier Excel « Comparaison… » via WeTransfer. J’ai dénombré 43165 anomalies.

**Comment by SiropOps** [comment]
Je ne sais pas quoi faire ?!

**Comment by cibotalista** [comment]
[COMPARAISON_INSTITUT_ORIGINE_JIC_VS_BOTALISTA_22_05_2020.xlsx](https://github.com/CJB-Geneve/cit-ticketing/files/5808421/COMPARAISON_INSTITUT_ORIGINE_JIC_VS_BOTALISTA_22_05_2020.xlsx)
