### ISSUE TITLE
[COL] Liste de rouge

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#759]
Url : https://g.botalista.community/#/collection/list/
Username : freyre

Description : Salut Cyril,

Voici la liste rouge 2016 pour créer un nouveau "projet" de collections (nouvelle checklist).

J'ai déjà appliqué un filtre sur les taxons menacés, ça fait 736 taxons menacés en Suisse, à mettre "en miroir" avec tous nos spécimens cultivés aux CJB.

À disposition pour plus d'explications si nécessaire.

Merci d'avance!

**Comment by SiropOps** [comment]
[Liste rouge 2016-Cyril.xlsx](https://github.com/CJB-Geneve/cit-ticketing/files/5854317/Liste.rouge.2016-Cyril.xlsx)
