### ISSUE TITLE
[REC] TICKET PARIS : TICKET_PARIS_RECHERCHE : TOUCHE" ; " _30_04_2020

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#763]
Url : https://jbp.botalista.community/#/harvest/list/
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Comme suite la réunion Paris/Genève de ce jour, je vous communique un ticket noté ??? sans numéro de ticket BLC.

"(nouveau test le 18/06), toujours présent dans la 1.7.2 - 1.8.6 idem -rapport de plantage dans la barre de recherche de BOTA-REC" lorsque la ponctuation ";" est insérée.

Bien cordialement 

Vincent LIPA

**Comment by SiropOps** [comment]
ça marche bien ?! https://jbp.botalista.community/#/harvest/list/?q=;
