### ISSUE TITLE
[TAX] TICKET_ERREUR GENERALE : LIEN HYPERTEXTE DWc-A _04_05_2020

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#764]
Url : https://jbp.botalista.community/#/taxon/edit/63942?tab=habitat
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Comme suite la réunion Paris/Genève de ce jour, je vous communique un ticket noté ??? sans numéro de ticket BLC.
"(Onglet Habitat) (nouveau test le 18/06) - bug présent dans la version 1.7.2, idem 1.8.6- en cliquant sur lien hypertexte, le système renvoie un rapport de plantage.

Cordialement 
Vincent Lipa

**Comment by SiropOps** [comment]
fonctionnalité plus opérationnel A réfléchir de la commission technique
