### ISSUE TITLE
[ACQ] Nom d'acquistion et cultivars

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#777]
Url : https://neu.botalista.community/#/acquisition/edit/
Username : ruch

Description : Bonjour Cyril,

pour l'utilisateur Ruch, il est possible de me répondre directement à mon adresse e-mail: nicolas.ruch@unine.ch

J'ai une petite question concernant l'introduction des épithètes de cultivars dans le nom d'acquisition. Je me souviens dans l'une des présentations de Botalista, le sujet des cultviars a été présenté car Paris en avait besoin. 
Je sais qui'il n'est pas possible d'avoir toutes les cultivars listés, mais je voulais savoir si il y a une méthode que vous utiliser? Directement dans nom d'acquisition en oubliant le fait que le nom accpté corresponde ou il y a un module à un autre endroit dans botista pour gérer ces noms.

Merci pour votre réponse. Je la communiquerai à Anne-Laure.

Salutations de Neuchâtel,

Nicolas

**Comment by RPalese** [comment]
Bonjour Nicolas,

Les noms de cultivars se gèrent comme n'importe quel nom au départ:

1. tu sélectionnes le nom latin souhaité (p. ex. Abies alba Mill.)
2. tu cliques sur "Ajouter un nom de rang inférieur"
3. tu sélectionnes le Rang taxonomique "cultivar"
4. tu écrisl'épithète de cultivar (p. ex. Pendula) 
5. tu sauvegardes
6. tu disposes maintenant du nom Abies alba Mill. 'Pendula'

Tu verras qu'à l'écran il y a un volet supplémentaire appelé "Cultivar" qui apparaît et qui te permets d'enregistrer des attributs propres aux cultivars (groupe horticole, pays d'obtention, etc.)

Tu peux voir cette exemple sur le bac à sable de Botalista

Cordialement

Raoul
