### ISSUE TITLE
[NOM] cultivar

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#783]
Url : https://bord.botalista.community/#/nomenclature/import/view/3
Username : vivent

Description : Bonjour Cyril,
dans le cas d'un cultivar, est-il nécessaire de les noter: Fortunella margarita (Lourd) Swingle 'Nagami' 
ou 
doit-on simplement valider le nom de genre et d'espèce, le cultivar ayant déjà été associé?

merci  Laura

**Comment by SiropOps** [comment]
Répondu par mail 05.03.2021 à 06.34 directement à Laura
