### ISSUE TITLE
[ACQ] Code IPEN

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#790]
Url : https://neu.botalista.community/#/acquisition/edit/
Username : oppliger

Description : Toutes les accessions de Fribourg ont un code IPEN transcrit de la même manière, sans trait d'union.
Il y a à chaque fois un avis comme quoi la construction du code est faux...?

**Comment by RPalese** [comment]
Bonjour Laurent,
Pourriez-vous me donner un exemple?

**Comment by RPalese** [comment]
Bonjour Laurent,

Le problème vient juste du fait que tu ne mets pas les "-" dans le code IPEN. J'ai créé une acquisition avec les mêmes informations que toi en écrivant le code IPEN "CH-0-FRIBG-20200324 " et ça passe tout droit.

Dis moi si ok de ton côté.

Cordialement

Raoul
