### ISSUE TITLE
[LOC] Menu déroulant : manque le Sous-groupe Europe-Sibérie 07

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#795]
Url : https://g.botalista.community/#/location/list/
Username : sibadmin

Description : Quand on cherche le Sous-groupe Europe-Sibérie 07, il n'apparait pas dans le menu déroulant ! Tous les autres Sous-groupe y sont... il faut alors aller le Rechercher dans la liste, ce qui fait des manipulations inutiles. Mais je sais qu'il y a des Sous-groupe d'autres Groupes qui manquent également...

**Comment by RPalese** [comment]
Je ne comprends pas bien Oû se trouve le problème: de quel menu déroulant parles-tu?

Essaye de faire une copie d'écran et de la lier à ce ticket pour que je comprenne un peu mieux.

Merci
