### ISSUE TITLE
[CULT] Impossible d'ouvrir la fiche du numéro 20181257N0

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#797]
Url : https://g.botalista.community/#/cultivated/list/
Error message : No enum constant com.botalista.cultivated.entity.enums.Container.enum_other; nested exception is java.lang.IllegalArgumentException: No enum constant com.botalista.cultivated.entity.enums.Container.enum_other
Username : staehli

Description : En cliquant sur le nom ou le numéro dans la recherche de spécimen cultivé, impossible d'ouvrir la fiche de cette plante (Alyssum L.) !!

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://g.botalista.community/api/cultivated/id/53423
Request method: GET
Status Code: 405 (Method Not Allowed)
Data send: 
 undefined
 Error Type: com.botalista.errors.container.CriticalError
Error message: 
 No enum constant com.botalista.cultivated.entity.enums.Container.enum_other; nested exception is java.lang.IllegalArgumentException: No enum constant com.botalista.cultivated.entity.enums.Container.enum_other

**Comment by SiropOps** [comment]
BD action
