### ISSUE TITLE
[LOC] Plantage général- Chionanthus retusus

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#802]
Url : https://g.botalista.community/#/location/view/156?tab=3
Error message : No enum constant com.botalista.cultivated.entity.enums.Container.enum_clay_pot; nested exception is java.lang.IllegalArgumentException: No enum constant com.botalista.cultivated.entity.enums.Container.enum_clay_pot
Username : freyre

Description : Je cherche à consulter le SC n°20120571N0 Chionanthus retusus, et le message d'erreur s'affiche systématiquement. J'ai essayé avec d'autres SC, ça fonctionne de manière aléatoire, certains sont consultables, d'autres marquent le même message d'erreur.

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://g.botalista.community/api/cultivated/id/36821
Request method: GET
Status Code: 405 (Method Not Allowed)
Data send: 
 undefined
 Error Type: com.botalista.errors.container.CriticalError
Error message: 
 No enum constant com.botalista.cultivated.entity.enums.Container.enum_clay_pot; nested exception is java.lang.IllegalArgumentException: No enum constant com.botalista.cultivated.entity.enums.Container.enum_clay_pot

**Comment by SiropOps** [comment]
DB action
