### ISSUE TITLE
[ACQ] Pays d'origine reste en "XX" dans n° IPEN malgré avis de changement

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#803]
Url : https://g.botalista.community/#/acquisition/edit/62170
Username : lehmann

Description : Bien que spécifié, le pays d'origine reste en "XX"dans le n°IPEN. Déjà plusieurs tickets émis pour ce même problème qui persiste.

**Comment by RPalese** [comment]
Constatant que le code IPEN pour cette acquisition est correctement construit (UZ-0-G-20210274), je clos le ticket.
