### ISSUE TITLE
[FUN] BOTA-ADMIN : Doublon de 'serre plateau' ID 45 ET 27

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#806]
Url : https://jbp.botalista.community/#/functionalunit/edit/45
Username : paris

Description : Bonjour les DEV de Botalista, 

Il est possible de créer des doublons des secteurs (ex : 'serre plateau' ID 45 et 27). Je ne peux pas  supprimer l'ID 45. Des SA y sont rattachés. Que puis-je faire  pour supprimer ce doublon ?

Cordialement 
Vincent Lipa

**Comment by Paris75012** [comment]
Rebonjour les DEV,

J"ai pu supprimer à l'affichage du secteur actif  "serre plateau" depuis le menu "Administration". 

Cordialement 

Vincent Lipa
