### ISSUE TITLE
[LOC] BOTA-SC  : Modification de groupe à sous-groupe (Iris historique-058)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#808]
Url : https://jbp.botalista.community/#/location/edit/45
Error message : could not execute statement; SQL [n/a]; constraint [ind_loc_uid]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Je rencontre un rapport de plantage suite à mon souhait de modifier l'emplacement (groupe à sous-groupe) "Iris historique-058".

Bonne journée

Cordialement 

Vincent Lipa

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://jbp.botalista.community/api/location/
Request method: POST
Status Code: 405 (Method Not Allowed)
Data send: 
 {"typeEntite":"Groupe","version":1,"oldID":[{"NO_EMPLACEMENT":"833"}],"idLocation":45,"uid":"fbec0948-3ade-4666-96eb-1d6c2ce5b1a0","name":"Iris historique-058","completeName":"Parc Floral Iris historique-058","parent":{"idLocation":6207,"typeEntite":"Place"},"active":true,"description":null,"temperature":null,"continentality":null,"luminosity":null,"humidity":null,"changingHumidity":false,"streamingWater":false,"soilStructure":null,"humus":null,"soilFertility":null,"soilComposition":null,"phReaction":null,"locationGeometry":null}
 Error Type: com.botalista.errors.container.CriticalError
Error message: 
 could not execute statement; SQL [n/a]; constraint [ind_loc_uid]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by Paris75012** [comment]
[TICKET_BOTA-SC_EMPLACEMENT_IRIS_HISTORIQUES_15_04_2021.docx](https://github.com/Computaceae-IT/cit-ticketing/files/6317820/TICKET_BOTA-SC_EMPLACEMENT_IRIS_HISTORIQUES_15_04_2021.docx)
