### ISSUE TITLE
[NOM] Impossible de rectifier l'orthographe d'une espèce

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#809]
Url : https://g.botalista.community/#/nomenclature/edit/44883
Username : lehmann

Description : peNNsylvanica et pas pensylvanica. Impossible de modifier l'orthographe. Message du système : "ce nom existe déjà" OUi ! Mais pas avec la bonne orthographe !
Merci d'avance.
Bonne journée.
al

**Comment by RPalese** [comment]
C'est bien normal que Botalista réagisse comme cela: le nom Fraxinus pennsylvatica (avec deux n) existe bien dans la BD (il y a les deux orthographes présentes...).

Par chance Fraxinus pensylvatica (avec un seul n) ne semble être rattaché à aucune acquisition: je vais donc demander à Cyril de le détruire.

En attendant, tu feras bien attention à sélectionner celui avec 2 n si tu en as besoin.

Salutations
