### ISSUE TITLE
[NOM] BOTA-NOM : Tests des réquêtes liées aux données des champs Obtenteur, Date d'obtention, Pays obtenteur et Nom commercial

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#815]
Url : https://jbp.botalista.community/#/nomenclature/list/
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Voici un premier retour de la mise en place de cette fonctionnalité dans le module de requête de BOTA-NOM. Quels que soient les champs listés dans le titre du ticket de support, il apparait les anomalies suivantes : 

- Ces champs n'apparaissent pas dans le résultat de la requête dans l'application.
 
- Ces champs ne sont pas sélectionnables dans le contrôle situé au-dessus de la colonne 'Nom complet'

- Ces champs n'apparaissent pas dans des colonnes séparées . Ils manquent les champs suivants dans l'export Excel: Obtenteur, Date d'obtention, Pays obtenteur et Nom commercial

- La liste déroulante des "Pays obtenteur" n'est pas ordre alphabétique. Nous avons :  Afghanistan, Finlande, Albanie)

- Recherche Obtenteur Meilland  (Détermination accepté  ROSA ×sp ? & Obtenteur 'Meilland'): 1 seul résultat dans BOTA-NOM. Nous avons 211 résultats en recherchant l'obtenteur MEI dans le champ 'Nom complet' sous Excel. Cette recherche a été faite à partir de BOTA-NOM.  

En lien avec le ticket 572

Bien cordialement 

Vincent Lipa

**Comment by Paris75012** [comment]
Quelques captures et Exports Excel 
![Screenshot_2021-05-06 Botalista Noms Recherchemeilland 4](https://user-images.githubusercontent.com/74540524/117273936-dd6c0400-ae5c-11eb-9493-1eb70a8a62da.png)
![Screenshot_2021-05-06 Botalista Noms Recherche2](https://user-images.githubusercontent.com/74540524/117273941-df35c780-ae5c-11eb-965a-6a225944a285.png)
![Screenshot_2021-05-06 Botalista Noms Recherche](https://user-images.githubusercontent.com/74540524/117273947-e066f480-ae5c-11eb-8d51-ed704b8ef478.png)
![Screenshot_2021-05-06 Botalista Noms Recherche3](https://user-images.githubusercontent.com/74540524/117274105-07bdc180-ae5d-11eb-85d0-152eaa41a77a.jpg)
[Copie de nomenclatureExport_MEILLAND_06-05-2021_08_58_41.xlsx](https://github.com/Computaceae-IT/cit-ticketing/files/6433329/Copie.de.nomenclatureExport_MEILLAND_06-05-2021_08_58_41.xlsx)
[Copie de nomenclatureExport_Date_Obtention_SUPERIEUR A 1900_06-05-2021_08_47_19.xlsx](https://github.com/Computaceae-IT/cit-ticketing/files/6433330/Copie.de.nomenclatureExport_Date_Obtention_SUPERIEUR.A.1900_06-05-2021_08_47_19.xlsx)

**Comment by Paris75012** [comment]
Bonjour Cyril, 

Pourquoi ce ticket est-il clôturé ?  Les anomalies relevées ne sont pas corrigées dans la version 2.1.4. 

Faut-il scinder toutes ces anomalies dans  des tickets séparés ? 

Bon début de semaine 

Bien à toi 

Vincent Lipa

**Comment by SiropOps** [comment]
Non, il faut attendre la version 2.1.5 de cette nuit ;-)

Salutations

**Comment by Paris75012** [comment]
Ok c’est noté !!! Merci beaucoup.. Je testerai donc cela demain matin…

Bon appétit

Bien Cordialement

Vincent Lipa
ASE aménagement paysager
Responsable de la graineterie du Jardin botanique de Paris


***@***.***CFE17D.4632F520]

Jardin botanique de Paris – Paris.fr<https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiYgMnC0qXaAhXIkywKHcbyAL4QFgguMAA&url=https%3A%2F%2Fwww.paris.fr%2Fjardinbotaniquedeparis&usg=AOvVaw108ymee_CTrfV65b7K05nw>

Bureau :
Ville de Paris
Direction des Espaces Verts et de l'Environnement
Service des Sciences et Techniques du Végétal Agriculture Urbaine
Jardin Botanique
103 avenue de  France
75639 PARIS Cedex 13
Fax : + 33 (0)1 71 28 57 41

Graineterie du Jardin botanique de Paris :
Pavillon 5 - Parc Floral  75012 Paris
Tél. : + 33 (0)1 49 57 94 47

De : Cyril Boillat ***@***.***
Envoyé : lundi 17 mai 2021 12:46
À : Computaceae-IT/cit-ticketing
Cc : Lipa, Vincent; Comment
Objet : Re: [Computaceae-IT/cit-ticketing] [NOM] BOTA-NOM : Tests des réquêtes liées aux données des champs Obtenteur, Date d'obtention, Pays obtenteur et Nom commercial (#815)

* Ce message a ete emis par un expediteur externe *
Prenez garde aux liens et aux pieces jointes. Ne fournissez jamais votre mot de passe de connexion Ville de Paris.

________________________________

Non, il faut attendre la version 2.1.5 de cette nuit ;-)

Salutations

**Comment by Paris75012** [comment]
Bonjour Cyril, 

Ci-dessous mes retours suite à la mise en place de la nouvelle version 2.1.5 (mes commentaires commencent par VL :

Voici un premier retour de la mise en place de cette fonctionnalité dans le module de requête de BOTA-NOM. Quels que soient les champs listés dans le titre du ticket de support, il apparait les anomalies suivantes :

    Ces champs n'apparaissent pas dans le résultat de la requête dans l'application. : 

    VL : Corrigé

    Ces champs ne sont pas sélectionnables dans le contrôle situé au-dessus de la colonne 'Nom complet' : 

     VL : Corrigé

    Ces champs n'apparaissent pas dans des colonnes séparées . Ils manquent les champs suivants dans l'export Excel: Obtenteur, Date d'obtention, Pays obtenteur et Nom commercial : 

     VL:  Corrigé 

    La liste déroulante des "Pays obtenteur" n'est pas ordre alphabétique. Nous avons : Afghanistan, Finlande, Albanie) :  

       VL : Correction partielle : - j'ai trouvé Zimbabwe puis Équateur, Érythrée et le dernier Îles Vierges britanniques"

    Recherche Obtenteur Meilland (Détermination accepté ROSA ×sp ? & Obtenteur 'Meilland'): 1 seul résultat dans BOTA-NOM. Nous avons 211 résultats en recherchant l'obtenteur MEI dans le champ 'Nom complet' sous Excel. Cette recherche a été faite à partir de BOTA-NOM.

       VL :  Ce n'etait pas une anomalie. Effectivement, l'obtenteur 'Meilland' n'est pas renseigné dans BOTA-NOM  (210 taxons de Rosa ×sp. ? MEI )  sauf pour 1 seul résultat !!!
[Copie de nomenclatureExport_18-05-2021_11_00_22.xlsx](https://github.com/Computaceae-IT/cit-ticketing/files/6500052/Copie.de.nomenclatureExport_18-05-2021_11_00_22.xlsx)


En résumé :  1 anomalie à corriger relative à l'ordre alphabétique "des pays obtenteur"

 Bien à toi 

 Vincent Lipa
