### ISSUE TITLE
[ACQ] "Pays" manquant

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#819]
Url : https://neu.botalista.community/#/acquisition/edit/
Username : oppliger

Description : Bonjour,
J'ai une accession dont l'ISO IPEN est YT.
Il s'agit de Mayotte, qui est un département français d'outre-mer.
Il n'est pas dans les propositions de pays, par défaut je vais mettre France, le système va grincer !
Peut-être faudrait-il le rajouter...?
Salutations et bonne semaine.
Laurent

**Comment by RPalese** [comment]
C'est effectivement une bonne question. Je regarde avec Cyril.
Raoul

**Comment by RPalese** [comment]
Les référentiels que nous utilisons considèrent les territoires d'outre mer comme appartenant à la France. Il faut donc attribuer le pays France et coller le code ISO YT au numéro IPEN. Le système va affectivement "grin^cer" mais si tu lui dis "oui" l'enregistrement se fera.

Cordialement

Raoul
