### ISSUE TITLE
[ACQ] Vérifier le namematching pour ce nom

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#820]
Url : https://ncy.botalista.community/#/acquisition/view/5066
Username : sibadmin

Description : Erreur sur une migration Drosera aliciae devient Drosera aliciae x capensis 
C'est visiblement le cas pour toutes les accessions !

**Comment by SiropOps** [comment]
J'ai vérifié, c'est "normal" car dans l'outil de Name matching, l'opération qui à été sélectionné est: _Sélectionner le nom existant_ **Drosera aliciae Raym.-Hamet** _et de l'éditer en_ **Drosera aliciae Raym.-Hamet × Drosera capensis L.**

Du coup, le nom **Drosera aliciae Raym.-Hamet** n'est plus dans la nomenclature; il a été modifié. https://ncy.botalista.community/#/nomenclature/list/?q=Drosera%20aliciae%20Raym.-Hamet

Pour moi, le seul moyen de s'assurer de la cohérence complète des données serait de partir de l'export de toutes les acquisitions et vérifier à la main ?! On pourrait ne prendre que les hybrides pour commencer ?! Ou on traite cas par cas quand on les voit, comme ici ?!

A vous de décider.
