### ISSUE TITLE
[CULT] BOTA-CULT : suppression impossible de SC "permission non autorisée"

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#835]
Url : https://jbp.botalista.community/#/cultivated/list/
Username : paris

Description : Bonjour Cyril, 
Il m'est impossible de supprimer des spécimens cultivés des SA SUIVANTS / 20210808J, 20210809J et 20210810J. Il s'agit des SC ci après : 

20210808C0
20210809C0
20210810C0

Botalista nous indique 'Permission non autorisée' -Cependant,  j'ai pu supprimer un SC 20210808C1, 20210809C1 et 20210810C1.

Je ne comprends pas pourquoi cela est-il possible sur les C1 et pas les C0.

Merci d'avance pour ton éclairage 

Bien à toi 

Vincent Lipa

**Comment by SiropOps** [comment]
Bonjour Vincent, il est impossible de supprimer des spécimens qui ont été mis en collection, on peut juste les tuer. C'est une volonté métier pour conserver l'historique. Je peux te le supprimer en base si tu veux ?!

++

Cyril

**Comment by Paris75012** [comment]
Bonjour Cyril, 
si tu peux me les supprimer en ajoutant le 20210810C4 et  20210809C2. Par ailleurs, j'ai constaté une anomalie d'affichage.
![Screenshot_2021-06-15 Botalista Spécimens cultivés Consultation 54166](https://user-images.githubusercontent.com/74540524/122346118-e6b2bb00-cf48-11eb-9af9-bb883792f2ee.png)

**Comment by Paris75012** [comment]
![Screenshot_2021-06-15 Botalista Spécimens cultivés Consultation 54160](https://user-images.githubusercontent.com/74540524/122346177-f6ca9a80-cf48-11eb-9cab-a3d543fa3a9b.png)

**Comment by Paris75012** [comment]
les 2 acquisitions J et T sont affichées à l'écran bien que celles-ci ne soient plus présentes dans les SA.
