### ISSUE TITLE
[ACQ] Mode de provenance : CITES

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#836]
Url : https://jbp.botalista.community/#/acquisition/list/?q=20210812T
Username : paris

Description : Bonjour Raoul, 

Botalista liste parmi les modes de provenance : CITES   
 
Dans quel cas cela s'applique-t-il ?  pour toutes les acquisitions accompagnées d'un permis ou certificat CITES ? 

Merci par avance

Bien à toi 
VIncent Lipa

**Comment by RPalese** [comment]
Bonjour Vincent,

Non, on utilise ce mode de provenance pour des plantes qui auraient été séquestrées en douane pour des raisons de réglementation CITES et confiées au Jardin botanique

Cordialement

Raoul

**Comment by Paris75012** [comment]
Bonjour Raoul, 

Merci beaucoup pour ta réponse explicite.

Bien cordialement 

Vincent Lipa
