### ISSUE TITLE
[ACQ] Bac à sable avec un jeu de données de Paris

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#837]
Url : https://jbp.botalista.community/#/acquisition/list/?q=20210812T
Username : paris

Description : Bonjour Raoul et Cyril, 

Serait-il possible de disposer pour nos futures formations BOTALISTA en interne  "d'un bac à sable" (sandbox) avec un jeu de de données du Jardin botanique de Paris ? 

Merci par avance de vos réponses 

Bien cordialement 

Vincent Lipa

**Comment by SiropOps** [comment]
Bonjour Vincent, oui il est possible d'avoir une instance bac à sable avec vos données. Il faut établir une planification date de début et de fin. Ensuite, l'opération (la création de l’instance) sera planifié dans un cycle de développement; en gros il faut me dire min 1 mois en avance pour être certain de disposer de l'instance pendant votre formation.
