### ISSUE TITLE
[REC] BOTA-REC : AJOUT DU CHAMP 'NUMERO DE SPECIMENS ACQUIS' dans le filtre élaboré

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#839]
Url : https://jbp.botalista.community/#/harvest/list/
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

En tant qu'utlisateur, je souhaiterais pouvoir faire une recherche à partir du 'NUMERO  DE SPECIMENS ACQUIS à partir du filtre élaboré de BOTA-REC.

Cordialement 

Vincent Lipa

**Comment by SiropOps** [comment]
Même réponse que #841 il faut ajouter des champs dans aquisition
