### ISSUE TITLE
[REC] BOTA-REC : ajouts des champs  'NUMERO SPECIMENS ACQUIS', 'NOM ACQUISITION' et 'DETERMINATION ACCEPTEE'

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#841]
Url : https://jbp.botalista.community/#/harvest/list/?q=2014
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

En tant qu’utilisateur, je souhaiterais pouvoir faire apparaitre dans l'exportation des récoltes les champs ' NUMERO  DE SPECIMENS ACQUIS',NOM ACQUISITION et DETERMINATION ACCEPTEE'.

Cordialement 

Vincent Lipa

**Comment by Paris75012** [comment]
![Screenshot_2021-06-17 Botalista Récoltes Recherche_841](https://user-images.githubusercontent.com/74540524/122357245-d9e79480-cf53-11eb-9ed0-33d7e9f81c01.png)

**Comment by SiropOps** [comment]
Bonjour Vincent, il n'est malheureusement pas possible de faire apparaître ces champs ici, car une récolte n'a pas forcément de d’acquisition liée ou potentiellement plusieurs. Si tu veux ces informations, il faut le ajouter dans l'écran de recherche d'une acquistion?!

**Comment by Paris75012** [comment]
Bonjour Cyril,

C’est noté.

Bien à toi

Vincent Lipa
ASE aménagement paysager
Responsable de la graineterie du Jardin botanique de Paris


***@***.***CFE17D.4632F520]

Jardin botanique de Paris – Paris.fr<https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiYgMnC0qXaAhXIkywKHcbyAL4QFgguMAA&url=https%3A%2F%2Fwww.paris.fr%2Fjardinbotaniquedeparis&usg=AOvVaw108ymee_CTrfV65b7K05nw>

Bureau :
Ville de Paris
Direction des Espaces Verts et de l'Environnement
Service des Sciences et Techniques du Végétal Agriculture Urbaine
Jardin Botanique
103 avenue de  France
75639 PARIS Cedex 13
Fax : + 33 (0)1 71 28 57 41

Graineterie du Jardin botanique de Paris :
Pavillon 5 - Parc Floral  75012 Paris
Tél. : + 33 (0)1 49 57 94 47

De : Cyril Boillat ***@***.***
Envoyé : vendredi 18 juin 2021 08:02
À : Computaceae-IT/cit-ticketing
Cc : Lipa, Vincent; Comment
Objet : Re: [Computaceae-IT/cit-ticketing] [REC] BOTA-REC : ajouts des champs 'NUMERO SPECIMENS ACQUIS', 'NOM ACQUISITION' et 'DETERMINATION ACCEPTEE' (#841)

* Ce message a ete emis par un expediteur externe *
Prenez garde aux liens et aux pieces jointes. Ne fournissez jamais votre mot de passe de connexion Ville de Paris.

________________________________

Bonjour Vincent, il n'est malheureusement pas possible de faire apparaître ces champs ici, car une récolte n'a pas forcément de d’acquisition liée ou potentiellement plusieurs. Si tu veux ces informations, il faut le ajouter dans l'écran de recherche d'une acquisition?!
