### ISSUE TITLE
[CULT] BOTA-SC : Export Excel du Correspondant rattaché au SC 20161263N3 (Pelargonium redactum)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#846]
Url : https://jbp.botalista.community/#/cultivated/view/47863
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Le correspondant du spécimen cultivé 20161263N3 (Pelargonium redactum) est bien renseigné dans le formulaire du SC.Cependant, il n'apparait pas dans l'exportation Excel.

Cordialement 
VIncent Lipa

**Comment by Paris75012** [comment]
![Screenshot_2021-07-05 Botalista Spécimens cultivés Consultation 47863](https://user-images.githubusercontent.com/74540524/124433432-06344b00-dd73-11eb-95e3-8d8ffc8131c1.png)
[Copie de cultivatedExport_Pelargonium_05-07-2021_09_14_42.xlsx](https://github.com/Computaceae-IT/cit-ticketing/files/6762469/Copie.de.cultivatedExport_Pelargonium_05-07-2021_09_14_42.xlsx)
