### ISSUE TITLE
[LOC] bug change of level of garden region

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#848]
Url : https://bern.botalista.community/#/location/edit/106
Error message : could not execute statement; SQL [n/a]; constraint [ind_loc_uid]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Username : schäfer

Description : Hi!

I tried to change the level of the garden region 04.05.04 from "Gruppe" to "Untergruppe". When I try to safe I get this error window popping up. 
Am I doing something wrong? Thank you for your help!

All the best,
Deborah

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://bern.botalista.community/api/location/
Request method: POST
Status Code: 405 ()
Data send: 
 {"typeEntite":"Groupe","version":2,"oldID":[{"BOGA_Gebiet_ID":"53"},{"BOGA_Verantwortliche_ID":"17"},{"Place":"04.05.04 Alpinum NE-Teil östlich Treppe Ost Arten des kontinentale Steppe"}],"idLocation":106,"uid":"16674f69-c7c2-4139-92ba-0b937a98ddce","name":"04.05.04 Alpinum NE-Teil östlich Treppe Ost - Asien (Baikal)","completeName":"Botanisches Institut Alpinum 04.05.04 Alpinum NE-Teil östlich Treppe Ost - Asien (Baikal)","description":"Alpinum NE-Teil östlich Treppe Ost - Asien (Baikal)","parent":{"idLocation":305,"typeEntite":"Place"},"active":true,"temperature":null,"continentality":null,"luminosity":null,"humidity":null,"changingHumidity":false,"streamingWater":false,"soilStructure":null,"humus":null,"soilFertility":null,"soilComposition":null,"phReaction":null,"formErrors":{"Aire":{"key":"Aire","value":null,"msg":"location_error_wrong_group_parent","type":"InconsistentValues","path":"","baseEntity":{"typeEntite":"Groupe","version":2,"oldID":[{"BOGA_Gebiet_ID":"53"},{"BOGA_Verantwortliche_ID":"17"},{"Place":"04.05.04 Alpinum NE-Teil östlich Treppe Ost Arten des kontinentale Steppe"}],"idLocation":106,"uid":"16674f69-c7c2-4139-92ba-0b937a98ddce","name":"04.05.04 Alpinum NE-Teil östlich Treppe Ost - Asien (Baikal)","completeName":"Botanisches Institut Alpinum 04.05.04 Alpinum NE-Teil östlich Treppe Ost - Asien (Baikal)","description":"Alpinum NE-Teil östlich Treppe Ost - Asien (Baikal)","parent":{"version":0,"idLocation":305,"uid":"941efd48-33ba-4e4e-88c6-537fb27f6ecd","name":"Asien","idSite":1,"site":"Botanisches Institut","code":"BOGA","idArea":16,"area":"Alpinum","idPlace":305,"place":"Asien","completeName":"Alpinum Asien","active":true,"typeEntite":"Place","sector":{"version":0,"key":"Katalog","value":"Katalog","idFunctionalUnit":0,"uid":"ce4a9048-1606-409b-86e1-979835226660","type":"enum_sector","name":"Katalog","site":"1","archive":false},"sectorName":"Katalog","parent":16,"value":"Asien","key":"Asien","description":null,"oldID":null},"active":true,"temperature":null,"continentality":null,"luminosity":null,"humidity":null,"changingHumidity":false,"streamingWater":false,"soilStructure":null,"humus":null,"soilFertility":null,"soilComposition":null,"phReaction":null},"linkedKeys":{"Aire":null}}},"locationGeometry":null}
 Error Type: com.botalista.errors.container.CriticalError
Error message: 
 could not execute statement; SQL [n/a]; constraint [ind_loc_uid]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by SiropOps** [comment]
Hi,
it was "normal", it was a bug, i fixed, you can please retry 

https://bern.botalista.community/#/location/edit/106

++
