### ISSUE TITLE
[COR] question gestion nombre d'individus en collection

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#849]
Url : https://neu.botalista.community/#/corresponding/view/984
Username : maire

Description : Quand tu as fait une mise en collection en 2015 de 100 individus d'un spécimen cultivé et qu'en 2021 il n'a en a plus que 80, tu peux mettre où cette info, y a t'il un champs dédié ?

On ne note pas aussi précisément dans la plupart des cas, mais dans certaines cas, on voudrait faire un suivi plus précis.
Merci !

**Comment by RPalese** [comment]
Hello Anne-Laure,
Je vois deux possibilités:
1. a) Tu édites la partie "Mise en collection" et tu mets à jour le "Nombre d'individus plantés" avec la valeur 80
    b) Tu édites ensuite le spécimen cultivé et tu indiques dans le champ "Remarque" qu'il y en avait 100 au départ
2. Tu édites le spécimen cultivé et tu indiques dans le champ "Remarque" qu'il n'y en a plus que 80

Je préfère largement la solution 2. puisqu'on ne change pas le nombre d'individus qu'il y avait à l'origine de la mise en collection.

Et dès que tu mets une remarque il y a l'onglet "Remarque(s)" qui apparaît sur la fiche du spécimen cultivé.

A très bientôt
