### ISSUE TITLE
[ACQ] utilisation champ Ancien numéro

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#852]
Url : https://neu.botalista.community/#/acquisition/edit/
Username : maire

Description : comment on utilise le champ ancien numéro? la valeur que je saisis : 97-238 n'est pas enregistrée avec ma donnée...

**Comment by SiropOps** [comment]
https://user-images.githubusercontent.com/35902374/130471899-cdfd86ce-b7fc-451c-80b2-06e9ddf63f1a.mp4

**Comment by SiropOps** [comment]
A très bientôt Anne-Laure
++
