### ISSUE TITLE
[CULT] BOTA-CUL :  701 spécimens vivants cultivés en G   (origines sauvage, horticole, Jardin et Sauvage (cultivé)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#853]
Url : https://jbp.botalista.community/#/cultivated/list/?q=%25G0
Username : paris

Description : Bonjour Les DEV, 

En consultant le CC des charges de BOTA-CUL, j'ai constaté que ce cas n'est pas listé dans les cas "D'un SA de type "Index seminum" dont le type de provenance est "XXX" -->La lettre passe de G à XX (ici G).

S'agit-il d'une anomalie ? Faut-il rajouter ce cas dans le CC ?

Je vous joindrai via GITHUB l'export Excel en question.

Cordialement 
Vincent Lipa

**Comment by Paris75012** [comment]
Bonjour Cyril, 
Pourrais-tu supprimer les SC vivants en GO ? La suppression manuelle est réalisable mais trop longue (682 restants).

Bien à toi 
Vincent Lip a

**Comment by Paris75012** [comment]
Bonjour Cyril, 
J'ai supprimé 'mano à mano' les  677 enregistrements sur les 682.  5 SC restent : permissions insufisantes
Ce ticket est à clôturer. 
Cordialement 
Vincent Lipa
