### ISSUE TITLE
[NOM] Error

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#855]
Url : https://bord.botalista-dev.ch/#/nomenclature/view/461230?tab=2
Error message : could not execute statement; SQL [n/a]; constraint [ind_names_taxon_unique]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Username : sibadmin

Description : null

**Comment by SiropOps** [comment]
Lors qu'on synonymise un nom accepté et qu'on essaie de changer le synonime:
Ex
On créer espèce A.
On accepte espèce A.
On créer espèce B.
On accepte espèce B.
On crée synonymie A=B.
On change la synonymie en B=A -> Error
