### ISSUE TITLE
[CULT] exportation étiquette de propoagation

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#859]
Url : https://bord.botalista.community/#/cultivated/view/174396
Username : kassen

Description : Bonjour est-il possible de sélectionner plusieurs spécimens cultivés (le mieux à partir du numéro d'enregistrement) pour sortir plusieurs étiquettes de propagation en même temps?

merci

**Comment by RPalese** [comment]
Hello Anne-Laure,
Un fois que tu obtiens une liste de SC's via l'outil de recherche, il te suffit de cliquer sur l'icône "Exporter la liste en pdf".
Raoul
