### ISSUE TITLE
[LOC] instance NE emplacement disparu

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#861]
Url : https://neu.botalista.community/#/location/list/
Username : maire

Description : Salut,
Dans le groupe Alpinum, on a un emplacement Apennins.
Il apparait encore pour quelques SC mis en culture, mais l'emplacement n'existe plus, si on clique dessus depuis le SC, on a un rapport de plantage.
n° BD 2778 par exemple.
Est-ce qu'il y a un souci, ou c'est nous qui avons supprimé l'emplacement sans faire exprès ?
merci

**Comment by RPalese** [comment]
Hello Anne-Laure,
Je ne vois pas trop le problème... qu'entends-tu par "n° BD 2778"?
Raoul

**Comment by al-maire** [comment]
Salut,
C'est le numéro de l'acquisition qui s'affiche dans la barre d'adresse.
Oui on ne sait pas ce qui s'est passé... mais on a refait le sous-groupe et on va corriger manuellement, donc je pense que l'on peut clore ce ticket.
Merci

**Comment by RPalese** [comment]
Ok. Je clos ce ticket!
