### ISSUE TITLE
[S.L] BOTA-SC : Pays d'obtention erronés dans l'export Excel (Iris ×germanica 'Perfection' et Princess Beatrice)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#866]
Url : https://jbp.botalista.community/#/
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

L'export Excel des 2 spécimens cultivés Iris ×germanica 'Princess Beatrice' et 'Perfection' affiche des pays d'obtention erronés (Ukraine pour les 2 SC). Depuis BOTA-NOM, le détail du nom Iris ×germanica 'Princess Beatrice' affiche le 'Royaume-uni' comme 'Pays d'obtention'.

Je reste à votre disposition pour de plus amples informations.

Bien à vous 

Vincent Lipa

**Comment by Paris75012** [comment]
[TICKET_BOTA_SC_PAYS OBTENTION_FAUX_30_09_2021.docx](https://github.com/Computaceae-IT/cit-ticketing/files/7276182/TICKET_BOTA_SC_PAYS.OBTENTION_FAUX_30_09_2021.docx)
