### ISSUE TITLE
[ACQ] BOTA-SC : Impossibilité de supprimer le parent

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#875]
Url : https://jbp.botalista.community/#/acquisition/edit/52722
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

Il est impossible de supprimer le parent du SC 20211583G. Je vous communique les vues et les explications relatives à cette anomalie.

Parent : 20130453N1

Cordialement 

Vincent Lipa

**Comment by Paris75012** [comment]
[TICKET_PARIS_875_SUPPRESSION_IMPOSSIBLE_PARENT_20130453N1_SC_20211583G.docx](https://github.com/Computaceae-IT/cit-ticketing/files/7363336/TICKET_PARIS_875_SUPPRESSION_IMPOSSIBLE_PARENT_20130453N1_SC_20211583G.docx)

**Comment by Paris75012** [comment]
Test ok dans la version 2.4.2 mais l'IPEN du parent est toujours présent. il faut le supprimer manuellement !!!
