### ISSUE TITLE
[CULT] BOTA-SC : l'emplacement 'Présentation générale Australie' a disparu !!! (Secteur : Serres contemporaines -Site : Auteuil)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#878]
Url : https://jbp.botalista.community/#/cultivated/view/55495
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

La chargé d'inventaire du site d' Auteuil  (Mme Christine Potrel) a constaté depuis ce matin, lors de l'enregistrement d'une nouveau SC,  (20209759H0) que l'emplacement "Présentation générale Australie" avait disparu.

Bien cordialement 

Vincent Lipa

**Comment by Paris75012** [comment]
Bonjour les DEV de BOTALISTA, 
Nous avons résolu l'anomalie. Ce ticket est à clôturer.

Cordialement 
Vincent Lipa
