### ISSUE TITLE
[NOM] corriger l'horographe d'un cultivar

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#896]
Url : https://bord.botalista.community/#/nomenclature/view/461262?tab=1
Username : kassen

Description : Comment puis-je corriger l'horographe d'un cultivar déjà enregistré.

Merci

**Comment by RPalese** [comment]
Bonjour Laura,
Il faut cliquer sur le bouton vert "Editer" en bas à droite et cela t'ouvre une fenêtre où tu pourras modifier le nom du cultivar.
Raoul
