### ISSUE TITLE
[lot] création de deux lots

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#899]
Url : https://rc.botalista-dev.ch/v2/fr/lot/edit/acquisition/1dcf8a93-cbab-406b-add2-ad807292554d
Username : rc

Description : je n'ai pas réussis à réaliser un deuxième lot. Comment devons-nous procéder si on veut un lot pour la banque de graine et un lot pour IS? merci

**Comment by SiropOps** [comment]
Hello,

pour créer des lots pour l'IS et la BS, il faut dupliquer l'acquisition, pour avoir une acquisition de TYPE Index seminum et une autre de TYPE banque de semence. Ensuite, à partir de chaque acquisition il est possible (pas encore pour le type banque de semance) de créer un lot. ++
