### ISSUE TITLE
[ACQ] Acquisition pour Index

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#912]
Url : https://neu.botalista.community/#/acquisition/view/3159
Username : maire

Description : Salut,
Est-ce que je comprends bien que pour faire les Index seminum dans Botalista, il faudra créer une acquisition G pour toutes les plantes à l'Index ?
Donc si je récoltes sur un SA des collections vivantes, je le dupliques avec Type d'acquisition = index seminum ? avant de créer un lot dasn stockage ?
Merci!
Merci

**Comment by RPalese** [comment]
Hello!
Non, il ne faut pas dupliquer ton SA puisque tu vas récolter des semences d'un SC --> il s'agit donc d'une nouvelle génération (pas le même bagage génétique que ton Sa d'origine)!
Donc quand tu récoltes les semences sur un SC, tu ouvre la fiche de ce SC, tu cliques sur "repiquage et multiplication", tu sélectionnes et crée une multiplication générative --> le système te crée automatiquement un nouveau SA de type "Provisoire" avec toutes les infos nécessaires héritées du SA d'origine. Tu sélectionnes Type d'acquisition = "Index seminum" et tu sauvegardes. Tu vas te retrouver alors sur la vue de ta nouvelle acquisition de type G et tu verras qu'en bas de l'écran tu as toute la filiation avec le SA d'origine et le SC sur lequel tu as effectué la récolte. Magique ;-) 

Te souhaite une belle année (maman?)
