### ISSUE TITLE
[S.L] BOTA-REC : La hiérarchie administrative  est eronée (SA 20164846G)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#923]
Url : https://jbp.botalista.community/#/
Username : paris

Description : Bonjour les DEV de BOTALISTA, 

La hiérarchie administrative du SA 20164846G est erronée. La région Provence-Alpes-Côte d'Azur est affichée pour ce SA collecté en Ïle-de-France. De plus, celle-ci apparait après l'entité 'Pays' (ici France métropolitaine).

Bien cordialement,

VIncent Lipa

**Comment by Paris75012** [comment]
[TICKET_PARIS_923_HIERARCHIE ADMNISTRATIVE_ERRONEE_16122021.docx](https://github.com/Computaceae-IT/cit-ticketing/files/7725311/TICKET_PARIS_923_HIERARCHIE.ADMNISTRATIVE_ERRONEE_16122021.docx)

**Comment by Paris75012** [comment]
Ce ticket est à clôturer. Après un nouveau test en date de ce jour, la hiérarchie administrative du SA 20164846G apparait correctement.
