### ISSUE TITLE
[COR] de la part de dominique

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#949]
Url : https://bord.botalista.community/#/corresponding/edit/148
Username : kassen

Description : serait-il possible lors de l'extraction des contacts que l'adresse soit codifiée au format adresse et non dans une seule et même ligne. Cela permettrait de facilité l'impression des adresse de nos contacts.
Merci

**Comment by SiropOps** [comment]
J'ai mis comme délimitateur ( | ).

Tout de bon
