### ISSUE TITLE
[USER] A partir de cette utilisateur

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#952]
Url : https://ncy.botalista.community/#/user/view/philippe%20chauvet
Username : beghoura

Description : Il ne peut pas créer d'emplacement à parti de ce profil.

**Comment by SiropOps** [comment]
![image](https://user-images.githubusercontent.com/35902374/150997562-cf6dcfb6-bfa3-42b1-819a-490babf6f699.png)

**Comment by SiropOps** [comment]
J'ai pu créer un emplacement sans soucis. Peut-être une erreur de manipulation?
