### ISSUE TITLE
[ACQ] BOTA-SC : Permissions insuffisantes pour effectuer cette opération

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#967]
Url : https://jbp.botalista.community/#/acquisition/view/54203
Username : paris

Description : Bonjour les DEV de Botalista, 

Une utilisatrice de BOTALISTA a rencontré un problème de 'permissions insuffisantes' lors de la tentative d’enregistrement  d'une nouveau SC lié à l'acquisition 20209822J. Cette utilisatrice (Dessommes) est rattachée au secteur Serre du Plateau (Site Auteuil). J’ai supprimé cette acquisition dans un premier temps. Puis, j'ai enregistré une nouvelle acquisition avec les mêmes données. Le résultat reste identique malgré l'enregistrement d'une nouvelle acquisition.

Le warning 'Permissions insuffisantes' affecte l’administrateur. Est-ce normal ? Je ne comprends pas pourquoi le système refuse  l'enregistrement d'un nouveau SC  après la création d'un nouveau SA par l’administrateur ?  

Je vous joindrai la capture d'écran.
 
Bien cordialement 

Vincent Lipa

**Comment by Paris75012** [comment]
![Capture web_27-1-2022_94814_jbp botalista community](https://user-images.githubusercontent.com/74540524/151752919-ce1d05ba-f122-4209-aec7-d23e23be5897.jpeg)
