### ISSUE TITLE
[ACQ] BOTA-SC : permissions insuffisantes

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#968]
Url : https://jbp.botalista.community/#/acquisition/view/54203
Username : paris

Description : Bonsoir Cyril, 

Je viens de réaliser un ticket à ce sujet. Mais, je n’ai pas reçu de ticket automatique de la part de BOTALISTA. Je rencontre une anomalie de permissions insuffisantes lors de la création d’un SC rattaché au SA 20209822J même  en supprimant puis créant un nouvel SA par l’administrateur. 

Qu’en penses-tu ? 

Cordialement 

Vincent Lipa

**Comment by SiropOps** [comment]
Je viens de tester ça marche
