### ISSUE TITLE
[CULT] Ajouter déterminateur seul dans Acquisitions

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#973]
Url : https://ncy.botalista.community/#/cultivated/view/150141
Username : berthold

Description : Salut Cyril,
J'ai déterminé une plante mais dans "Liste de Déterminations" -> "Déterminé par" il existe uniquement le choix de choisir dans "Collectif de personnes"....je sais que j'ai plusieurs personnes dans ma tête mais ils sont tous Carl Berthold ;p

**Comment by SiropOps** [comment]
Suite réunion 15.03.2024
