### ISSUE TITLE
[NOM] "Synonymie" can not be changed

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#977]
Url : https://bern.botalista.community/#/nomenclature/view/172399?tab=2
Error message : could not execute statement; SQL [n/a]; constraint [ind_names_taxon_unique]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Username : schäfer

Description : I tried to change which species name is set as the accepted name and which one is set as the synonym. Trying to save the change I received an Error message. Thank for helping me figure out why I can save this change!
All the best,
Deborah

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://bern.botalista.community/api/nomenclature/synonym/process/force/
Request method: POST
Status Code: 405 ()
Data send: 
 {"idNodeParent":179403,"pov":1,"mode":"switch"}
 Error Type: com.botalista.errors.container.CriticalError
Error message: 
 could not execute statement; SQL [n/a]; constraint [ind_names_taxon_unique]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by SiropOps** [comment]
Duplicated ID in database
