### ISSUE TITLE
[NOM] Impossible de définir un nom comme accepté

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#981]
Url : https://ncy.botalista.community/#/nomenclature/view/395802?tab=2
Error message : could not execute statement; SQL [n/a]; constraint [ind_names_taxon_unique]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Username : beghoura

Description : Rapport de plantage dès que je veux modifier la synonymie (passer ginala en nom accepté courant).

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://ncy.botalista.community/api/nomenclature/synonym/process/force/
Request method: POST
Status Code: 405 ()
Data send: 
 {"idNodeParent":395047,"pov":3,"mode":"switch"}
 Error Type: com.botalista.errors.container.CriticalError
Error message: 
 could not execute statement; SQL [n/a]; constraint [ind_names_taxon_unique]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by SiropOps** [comment]
Problème de doublon d'ID en base de données
