### ISSUE TITLE
[CULT] problème de lenteur sur l'indexation des personnes (jardiniers, personnes, etc)

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#985]
Url : https://ncy.botalista.community/#/cultivated/edit/141307
Username : beghoura

Description : En rentrant mon nom dans la case "jardinier", cela peut prendre un certain temps avant affichage. 
Edit : tout ce qui a attrait à un nom

**Comment by SiropOps** [comment]
Reésolu
