### ISSUE TITLE
[ACQ] crash

### ISSUE THREAD

**Issue by cibotalista** [Computaceae-IT/cit-ticketing#999]
Url : https://ncy.botalista.community/#/acquisition/edit/
Username : berthold

Description : un crash dans l’écran de création d'une acquisition - la base était un peu lente avant de faire ce crash (l’icône de loading n’arrêtait as)

**Comment by cibotalista** [comment]
### Error details 

 Request url: https://ncy.botalista.community/api/filter/module/acquisition
Request method: GET
Status Code: 504 (Gateway Timeout)
Data send: 
 undefined
 Error Type: undefined
Error message: 
 undefined

**Comment by SiropOps** [comment]
J'étais en pleine mise à jour de l'application
